### ISSUE TITLE
Build YAML definitions permissions

### ISSUE THREAD

**Issue by mswehli** [Microsoft/azure-pipelines-agent#1622]
on VisualStudio.com
Can you let me know if it might be possible to set permissions for who can trigger the creation of a build definition by adding a .vsts-ci.yml file when Build YAML definitions is turned on in the preview features panel.
I.e: Can anyone with push privileges for a repo upload a .vsts-ci.yaml file, which in turns creates the build definition, or does the person who checked in the file and pushed the changes have to have build definition creation privileges?

**Comment by TingluoHuang** [comment]
@chrisrpatterson @bryanmacfarlane

**Comment by ericsciple** [comment]
@vtbassmatt

**Comment by vtbassmatt** [comment]
Simple answer: in a config-as-code world, the repo is the security boundary. If someone can land code in your repository, assume they can create the first build definition.

Complete answer: build definition security is still enforced. So imagine a user without that permission manages to get a .vsts-ci.yml file into master. We won't create a build definition right away. But eventually someone *with* that permission will create a branch off master which includes the new .vsts-ci.yml file. When that person pushes their branch, the build definition will get created. This doens't mean people can create arbitrary build definitions, though. We only watch for well-known filenames.

The above assumes VSTS. For non-VSTS Git repos, it's a little different because you have to create the build definition on the VSTS side before you've connected to the repo.

**Comment by TingluoHuang** [comment]
We have created a new repository for all YAML related issues, please move the current issue to there.
https://github.com/Microsoft/azure-pipelines-yaml
