### ISSUE TITLE
BYOS feedback

### ISSUE THREAD

**Issue by phgache** [microsoft/azure-pipelines-agent#1700]
This is a great idea because bringing customization and scalability to VSTS agent is a must have for us. Especially on the private side because we actually have networking requirements which don't allow us to use Hosted ones. 
We actually have around 10 vm used to run build and maintaining them up to date is a pain.

We are currently thinking about using Docker on Kubernetes to host build agents. 
Why have you choose to host agent on IaaS over Docker ? From my perspective containers are a lot more flexible and the provisioning time is faster. 

I have also noticed that you plan to provide elasticity based on the pool usage. I am wondering how you plan to achieve this feature because actually I don't see any solution out of the box. But this is a key feature I think as the build usage varies a lot.

**Comment by bryanmacfarlane** [comment]
Agreed on containers.  We have a POC working end to end where Kubernetes is build infra.  So we are planning to do that as well.  probably after ...

We are going to achieve elasticity by implementing a new pool provider interface - the provider just implements alloc / release.  Details later but the BYOS provider will have your subscription (service endpoint), image you want to use, and config settings min, max, idle, lifetime etc...  That provider will know how to create a machine in azure.  But much of the scale down and up could be just stopping / starting machines.

So pool types will be extensible and we will probably offer private, hosted, byos and then kubernetes.

**Comment by chrisrpatterson** [comment]
@melcom the challenge with containers with most of the build workloads we see in VSTS is people seem to expect a VM.  For example, the current Linux pool actually runs in containers but we get regular complaints and issues from customers who are trying to build and test a container but because of the fact the agent is already in a container they are not able to understand the networking configuration.

**Comment by melcom** [comment]
@bryanmacfarlane that is a great news because we are waiting this kind of feature. We are currently thinking how to replace our VM by containers but the next step will be elasticity. 

@chrisrpatterson I understand the network complexity but I think that hosting containers will provide a more clear understanding of the underlaying infra and so mitigate this point.

**Comment by bryanmacfarlane** [comment]
@melcom - we will do both! :)

**Comment by Evangelink** [comment]
Any news on this subject?

**Comment by bryanmacfarlane** [comment]
@Evangelink - the feature is currently lower on the backlog.  Any feedback on the need will help to prioritize it.

**Comment by Evangelink** [comment]
Hi @bryanmacfarlane,

At SonarSource we are moving most of our non .net builds to [Cirrus CI](https://cirrus-ci.org/) associated to Google Cloud Platform. We started to move the .net ones to VSTS and we are currently relying on the free agents but the performance are really not great for the number of PR/branches we do per day so being able to move to more powerful on-demand machines would be a big plus for us. Note that we don't want to spend (lose) time on maintaining a fleet of machines (for which we would have to be careful about security because of the internet access) and we do prefer spinning-up and trashing machines.

I hope the explanation of our use case is clear enough.

Note that as you could have understood reading between the lines, if there is another solution (in the pipe or with a higher priority in your backlog) allowing us to have (pay) for machines we don't have to manage and with better characteristics we are interested.

**Comment by hacst** [comment]
We would definitely love the possibility to use something like a on-prem Kubernetes cluster as a backend for a dynamic agent pool. The current way the pools handle is very inflexible.

**Comment by damccorm** [comment]
Hey, thanks for the feedback - we're tracking this internally and it should be coming soon. I'm going to close here since the feedback has been propogated internally.
