### ISSUE TITLE
Agent gets stuck and hangs  if automatic upgrade fails 

### ISSUE THREAD

**Issue by melezhik** [Microsoft/azure-pipelines-agent#1840]
## Have you tried trouble shooting?
yes

## Agent Version and Platform
any version before 2.140.0 , have not tested yet for this version 

Windows OS

## VSTS Type and Version
VisualStudio.com

## What's not working?

Based on #1696, especially https://github.com/Microsoft/azure-pipelines-agent/issues/1696#issuecomment-422417049  

Agent gets stuck and hangs without EASY way to roll it back to the previous version ( unless manual cleanup and reinstall ) if for some reasons agents fails to autoupdate.

**Comment by bryanmacfarlane** [comment]
Updating an agent (copying down files, updating the service, etc...) is not an atomic operation.  We have as many efforts to retry and absorb failures but if something fails in the script to run those sequence of steps fail, there isn't many options.

I'm afraid this issue is not actionable.  

We do have a way to rollback, it's an xcopy copy extract and run config.

**Comment by melezhik** [comment]
> We do have a way to rollback, it's an xcopy copy extract and run config.

It would be nice if agent handle this

I have around 6-7 agents get stuck every 2-3 weeks due autoupdate failure , and manual rollback is real chore.

**Comment by TingluoHuang** [comment]
@melezhik do you happen to know what is causing the auto-update failure? proxy/firewall?
