### ISSUE TITLE
Optimize the "Stop Container" step

### ISSUE THREAD

**Issue by Naninani** [Microsoft/azure-pipelines-agent#1916]
## Having issue with Tasks?
**Stop Container**

## Agent Version and Platform
Version of your agent? **2.140.2** - **self-hosted agent**

OS of the machine running the agent? **Linux**

## VSTS Type and Version
**MS Teams internal VisualStudio.com account**

## What's not working?
**Issue 1**:
Currently, on VSTS Hosted pools and in some cases on self hosted pools, the stop/delete of the container and network is taking a lot of time - up to 4 min. There are no services running in our containers that could cause that. The issues might be related to the way how the containers are 1st stopped and then deleted.
**Suggested Solution**:
A better approach would be not to stop the container at all, but to forcefully delete it using
`docker rm -f <container name>`
That would save time.
Also ensure that the VSTS hosted agents are configured to use "overlay2" as storage driver.

**Issue 2**:
Currently if a build is canceled, sometimes the "**Stop Container**" step is not executed. This leaves the containers on the host running, which makes subsequent builds fail as the "**Initialize Container**" task is always trying to create a container with the same name. It also leaves the networks hanging and polluting the host.
**Suggested Solution**:
1. Always create a container with unique name. i.e. **\<build definition name\>-\<build ID\>**.
2. Ensure the "**Stop Container**" task always runs.
3. Provide an optional feature via yaml flag to prune all exited containers and networks:
 - Flag name: **prune [OPTIONS: true/false]**
 - Capability: Default to **false**. If **true**, set the docker commands in the "**Stop Container**" to:
`docker container prune --force`
`docker network prune --force`
Above will ensure all containers and networks are pruned - especially useful on self hosted agents.

**Issue 3**:
Container memory limit cant be set on VSTS Linux hosted pools.
`options: '--memory=<some vaule>GB'`
**Suggested Solution**:
1. Append **cgroup_enable=memory swapaccount=1** at the end of the  GRUB_CMDLINE_LINUX_DEFAULT variable in /etc/default/grub.
2. Add **cgroup_enable=memory swapaccount=1** to GRUB_CMDLINE_LINUX variable in /etc/default/grub.

Code:
```
#!/usr/bin/env bash

# string that needs to be appended to the grub file
append_grub_string='"cgroup_enable=memory swapaccount=1"'

# grub file path
grub_file_path=/etc/default/grub

# get the existing value for the key GRUB_CMDLINE_LINUX_DEFAULT
find_grub_key=$(grep -Po "(?<=^GRUB_CMDLINE_LINUX_DEFAULT).*" $grub_file_path)

# remove trailing characters
current_val=`echo -n $find_grub_key | tail -c +2 | head -c -1`

# append the string
modified_val=$current_val" "`echo -n $append_grub_string | tail -c +2`

# write back to the file
sudo sed -i "s/^\(GRUB\_CMDLINE\_LINUX\s*=\s*\).*\$/\1$append_grub_string/" $grub_file_path
sudo sed -i "s/^\(GRUB\_CMDLINE\_LINUX\_DEFAULT\s*=\s*\).*\$/\1$modified_val/" $grub_file_path

# update the grub settings
sudo update-grub
```
3. Restart the agent.

## Agent and Worker's Diagnostic Logs
**Issue 1 logs**:
```
2018-10-19T21:46:05.0386291Z Stop container: <container name>
2018-10-19T21:46:05.0414147Z ##[command]/usr/bin/docker stop 47056ff4fcb009e6eacfa6f7da53e2a1e78e1ad38d384564eadb68d63fcf42f4
2018-10-19T21:46:18.3155340Z 47056ff4fcb009e6eacfa6f7da53e2a1e78e1ad38d384564eadb68d63fcf42f4
2018-10-19T21:46:18.3657328Z ##[command]/usr/bin/docker rm 47056ff4fcb009e6eacfa6f7da53e2a1e78e1ad38d384564eadb68d63fcf42f4
2018-10-19T21:48:46.8033693Z 47056ff4fcb009e6eacfa6f7da53e2a1e78e1ad38d384564eadb68d63fcf42f4
2018-10-19T21:48:46.8646500Z ##[command]/usr/bin/docker network rm vsts_network_1d62381110144052b5af11cfe5be0fe4
2018-10-19T21:49:38.6991090Z vsts_network_1d62381110144052b5af11cfe5be0fe4
```

**Issue 2 logs**:
```
2018-10-19T20:18:53.7228256Z Error response from daemon: Conflict. The container name "/<image name>" is already in use by container "f23f672c625e501274abd2dbaec73d24678de505169cf7e3b5148b4d54013dd3". You have to remove (or rename) that container to be able to reuse that name.

2018-10-19T20:18:53.7949213Z ##[error]Exit code 1 returned from process: file name '/usr/bin/docker', arguments 'create --name <image name> --network=vsts_network_556dd542f3c9439e89f007d3a5e65ecd -v /var/run/docker.sock:/var/run/docker.sock --cpus=3   -v "/usr/local/vsts-agent/2":"/__w/2" -v "/usr/local/vsts-agent/_temp":"/__w/_temp" -v "/usr/local/vsts-agent/_tool":"/__t" -v "/usr/local/vsts-agent/_tasks":"/__w/_tasks" -v "/usr/local/vsts-agent-install/externals":"/__a/externals":ro -v "/usr/local/vsts-agent/.taskkey":"/__w/.taskkey" <image name> "/__a/externals/node/bin/node" -e "setInterval(function(){}, 24 * 60 * 60 * 1000);"'.
```

**Issue 3 logs**:
`2018-10-19T20:13:04.4098974Z WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.`

FYI: @TingluoHuang

**Comment by TingluoHuang** [comment]
> Issue 1:
Currently, on VSTS Hosted pools and in some cases on self hosted pools, the stop/delete of the container and network is taking a lot of time - up to 4 min. There are no services running in our containers that could cause that. The issues might be related to the way how the containers are 1st stopped and then deleted.
Suggested Solution:
A better approach would be not to stop the container at all, but to forcefully delete it using
docker rm -f <container name>
That would save time.
Also ensure that the VSTS hosted agents are configured to use "overlay2" as storage driver.

Base on the log, the most time is wasted at `docker rm`
`docker stop` will send `SIGTERM` and wait for 10 sec before sending `SIGKILL` to container.
`docker rm -f` will send `SIGKILL` first before rm the container, so looks like even we switch to use `docker rm -f` we will only save about 10 seconds compare the total 2-5 mins.
i would prefer use that 10 sec to give the container a chance to gracefully shutting down.

>Issue 2:
Currently if a build is canceled, sometimes the "Stop Container" step is not executed. This leaves the containers on the host running, which makes subsequent builds fail as the "Initialize Container" task is always trying to create a container with the same name. It also leaves the networks hanging and polluting the host.
Suggested Solution:
Always create a container with unique name. i.e. <build definition name>-<build ID>.
Ensure the "Stop Container" task always runs.
Provide an optional feature via yaml flag to prune all exited containers and networks:
Flag name: prune [OPTIONS: true/false]
Capability: Default to false. If true, set the docker commands in the "Stop Container" to:
docker container prune --force
docker network prune --force
Above will ensure all containers and networks are pruned - especially useful on self hosted agents.

I think `docker container prune` might not able to fix all the issues, since it only delete stopped container. you might have case where the agent even fail to stop the container and leave it running.
I will start tracking the container that agent created, so we can make sure it get cleaned up.

>Issue 3:
Container memory limit cant be set on VSTS Linux hosted pools.
options: '--memory=<some vaule>GB'
Suggested Solution:
Append cgroup_enable=memory swapaccount=1 at the end of the GRUB_CMDLINE_LINUX_DEFAULT variable in /etc/default/grub.
Add cgroup_enable=memory swapaccount=1 to GRUB_CMDLINE_LINUX variable in /etc/default/grub.

Thanks for the information, we will add these to our hosted image generation process.

**Comment by TingluoHuang** [comment]
close this issue since 2.144.0 agent has released to the service with the fix.
