### ISSUE TITLE
VSTS agent supports Windows 10 ARM32v7

### ISSUE THREAD

**Issue by philipktlin** [microsoft/azure-pipelines-agent#2062]
I needed to run VSTS agent on Windows 10 IoT Core (ARM32v7).  Based on my understandings, it is easy to support win-arm for VSTS  agent; only need to upgrade Agent.Service project to .Net Core 2.1 and related build script (I already did locally).  However, there are many external dependencies, e.g. Git, NodeJS.

Questions:
1. Do you have any plan to support VSTS agent on Windows ARM32v7?
2. Do you know any other workaround/trick to allow those externals to run on Windows ARM32v7?

**Comment by TingluoHuang** [comment]
As you noticed, make the agent compatible with Windows ARM is relative easy, the problem is mainly on our external dependencies, like Git.
https://github.com/git-for-windows/git/issues/1157

So, i don't think we can have an Windows ARM agent in short term, the closest solution i can think is use Remote PowerShell to do remote execution into the ARM device.

**Comment by TravisEz13** [comment]
FYI @adityapatwardhan

**Comment by vtbassmatt** [comment]
We're moving to .NET Core 3.1 shortly. While I don't have plans to ship a Windows ARM32 build (since x86 emulation seems to work pretty well), I'm not opposed to it. We would likely still rely on x86 emulation for dependencies like Git and Node -- would that be acceptable?

**Comment by philipktlin** [comment]
understood the difficulties.  For now I am using another vsts agent to deploy bits to Windows ARM32 device using remote powershell.

**Comment by TravisEz13** [comment]
PowerShell still needs this to test the scenario that @philipktlin is saying that he is using.

**Comment by mthalman** [comment]
Can we please keep this issue open?  My team's scenario involves the building/testing of .NET Docker ARM images.  Right now we need to have a Linux agent machine that communicates with a remote ARM device.  We'd really like to simplify our infrastructure by simply having the ARM device act directly as the agent.

**Comment by vtbassmatt** [comment]
Sure, let's leave it open a bit longer to see if we can fit it in.

**Comment by jtpetty** [comment]
@vtbassmatt - Now that we have switched the agent to use .NET Core 3.1, is this issue complete?

**Comment by vtbassmatt** [comment]
Let's hear from the community whether using x86 emulation is good enough. I'm not highly inclined to add a Windows/ARM flavor unless there's specific demand for it.

**Comment by TravisEz13** [comment]
I still refer to https://github.com/microsoft/azure-pipelines-agent/issues/2062#issuecomment-584989073

**Comment by azchohfi** [comment]
@vtbassmatt Is this the same issue to track Windows 10 on ARM64?

I I'm absolutely fine with having x86 emulation for certain dependencies, as long as perf is acceptable, which seems to be the case. Releasing a version of the agent that supports Windows on ARM64 would improve perf a little bit, which I honestly think its a win by itself. My scenario is not to build the ARM64 binary, which can always be done on x64 host machines, but to actually run the tests on the real physical hardware. Is there anything blocking this from being released? It doesn't seem a lot of work.

**Comment by vtbassmatt** [comment]
@azchohfi this issue was originally for ARM32. In the interest of not proliferating issues, I won't open a second one for ARM64 until/unless we decide to do something different for 32/64. Feel free to discuss here.

The pre-reqs we need are:
- .NET Core native support for the platform (which I believe is coming in .NET 5.0, while we're on 3.1)
- A usable Git build
- A usable Node 10, Node 14, and (not a hard requirement but a _very very very nice to have_) Node 6 build
- Hardware the team can use for build and test

Of these, the first is the hardest. We don't upgrade .NET versions willy-nilly, since it can impose a burden on everyone with a self-hosted runner. But assuming we move the agent to .NET 5 eventually anyhow, then it would be a matter of sourcing the right hardware that we can use for our build/test farm. I assume we can use Git and Node from Win/x86 with acceptable performance, but we'd of course have to test that as well.

I guess I'd turn it back and say - what do you gain by having a "native" agent to use for testing your bits? As long as the agent runs with acceptable performance AND can launch your processes natively, would it matter?

**Comment by azchohfi** [comment]
That is a fair point. I'm not sure if these reasons are enough to back the cost of this, but they might:
1) Having the agents support ARM64 is a first step for having ADO support it as well, in the future, eventually. Perf on hosted builds do have a cost, so any time we gain by having a native ARM64 binary is valuable.
2) One of the value propositions of Windows on ARM(64) is improved battery life. Again, x86 emulation have a cost, and for specific test scenarios, the x86 emulation might interfere with these results.
3) x86 processes are limited to <4GB of RAM, so having node natively on ARM64 could interfere with custom tasks that do their work inproc. Same goes for the agent itself.

Since the agent is only an orchestrator, I don't think its a hard requirement, but if the work to support it is minimal, why not?

**Comment by vtbassmatt** [comment]
Appreciate hearing your thinking, thanks! The "why not" is the other 90 zillion things I could ask the team to build 😁  It comes down to the <strike>science</strike> art of deciding what has the most impact: the little thing that helps everyone, the big thing that helps one person, or the splashy thing that attracts a bunch of new people?

**Comment by azchohfi** [comment]
If resourcing is an issue, is this something the team would accept a PR for? I'm up for it.

**Comment by vtbassmatt** [comment]
We had an offline chat about this. It's not really about resourcing per se.

**Comment by ntindle** [comment]
Hello, trying to set up our runners for Windows on Arm. Turns out Azure Pipelines doesn't support ARM. The specs of the PC are below. I would really like to see this feature added if Microsoft is serious about its future on ARM as we use azure pipelines to build our windows software.


Processor	Snapdragon (TM) 8cx Gen 2 @ 3.15 GHz   3.15 GHz
Installed RAM	16.0 GB (15.6 GB usable)
System type	64-bit operating system, ARM-based processor
