### ISSUE TITLE
slow performance nuget restore

### ISSUE THREAD

**Issue by thdotnet** [microsoft/azure-pipelines-agent#2134]
I would like to know if there's a way to improve the performance for a nuget restore using a private repo. It's taking several minutes to restore my packages, while restoring from nuget.org only take a few seconds. Is there something that I could do to decrease the amount of time spent in this task?

**Comment by TingluoHuang** [comment]
@thdotnet your problem might not scope to the agent, and you might want to seek help from https://developercommunity.visualstudio.com/spaces/21/index.html

I think you are using the Hosted agent, since it's fresh VM for every build.
I think the restore speed might depends on where your private nuget feed is located and where the Hosted agent machine is located.
The public nuget.org might have CDN all around the world.

**Comment by nathan-alden-hp** [comment]
This seems like a persistent problem especially for .NET Core/.NET Standard projects that have tons of dependencies. I'm frequently seeing "100000" timeouts in my NuGet restore tasks for very basic .NET Core solutions.

**Comment by TingluoHuang** [comment]
please open a ticket at the developer community since this is not scoped to the pipeline agent itself.
https://developercommunity.visualstudio.com/spaces/21/index.html
