### ISSUE TITLE
Windows agent should be configured for Windows Certificate Store by default

### ISSUE THREAD

**Issue by lg2de** [microsoft/azure-pipelines-agent#2194]
## Agent Version and Platform
2.136.1

OS of the machine running the agent?
Windows

## Azure DevOps Type and Version
on-premises TFS
16.131.28226.3

## What's not working?
To get the windows agent to run completely with a TFS server using self-signed SSL certificate I need to configure manually:
```
config.cmd --gituseschannel --sslcacert ./locationtoyourcert.pem
```

The one option is required for git fetch, the other is required to (explicitly download artifacts e.g. using 'Download Build Artifacts' task).

Is it possible to configure the agent by default to use the Windows Certificate Store?

**Comment by TingluoHuang** [comment]
@lg2de that's a little bit hard, the agent is an dotnet core application, it's already use Windows cert store. the problem is all the different tools you may use during your pipeline, i don't think there is a universal way to force everything to use windows cert store, plus some linux tool that built on old version openssl may not support windows cert store at all. :)

**Comment by lg2de** [comment]
1. The package is for window, so it "knows" it is for windows.
2. The batch file (config.cmd) is specific for windows. I could set required options internally.

**Comment by TingluoHuang** [comment]
i am talking about all the different tools you used during the build, like npm, node, python, go, etc, they may have no idea about windows certificate store. :)

**Comment by lg2de** [comment]
I'll create a PR to illustrate my thoughts.

**Comment by lg2de** [comment]
@TingluoHuang I analyzed the code.
I found that the option `gituseschannel` is for Windows only.
I do not see any reason why we should not use SChannel by default.
Would you accept a PR changing default behavior?
Do we need an option to disable SChannel by default?

**Comment by TingluoHuang** [comment]
@vtbassmatt to help. :)

**Comment by vtbassmatt** [comment]
Seems like a potentially back-compat breaking change with very limited positive effects. Unlikely to take that as a PR, sorry.

**Comment by lg2de** [comment]
@vtbassmatt, I wonder how you come up with "limited positive effects".
I can't imagine who wouldn't want to use the certificate store in Windows.

**Comment by vtbassmatt** [comment]
@lg2de it's limited because, for anyone for whom this matters, they're already specifying `-gituseschannel` at config time. For everyone else, the change is neutral (vast majority of cases) or potentially harmful (misconfiguration where OpenSSL knows about a corporate root CA but Windows cert store doesn't, for example).

Yes, I wish SChannel was the default on Windows. And we're looking at ways to safely introduce that change.

**Comment by A-AontwSR** [comment]
@vtbassmatt I doubt if many users are specifying -gitusschannel when configuring the Agent.

This option is nowhere mentioned in the docs and not mentioned in the config.cmd --help. How would they know about this option?
Except by searching the Agent's source code and finding this issue. At least that's how I found out.

Please document this usefull option!

**Comment by vtbassmatt** [comment]
Hm, it should be reported in help now. I'll investigate why it's not.

**Comment by vtbassmatt** [comment]
Ah, got it. We didn't actually replace our hard-coded help page in the agent. I'll go get this one added.

**Comment by vtbassmatt** [comment]
https://github.com/microsoft/azure-pipelines-agent/pull/2940
