### ISSUE TITLE
Question: Sharing _tool folder amongst agents

### ISSUE THREAD

**Issue by dschuermans** [microsoft/azure-pipelines-agent#2328]
## Agent Version and Platform
2.136.1

OS of the machine running the agent? OSX/Windows/Linux/...
Windows Server 2016

## Azure DevOps Type and Version
on-premises TFS/Azure DevOps Server?
Version 16.131.28226.3

## Question
So we got our own little on-premise VM for our team, that we use as a build server.
It's all good and dandy, wasn't it for the fact that IT had to frequently increase the disk space on the machine..
Since we're planning to move to Azure by the end of the year, they asked me to investigate why we keep needing more disk space.
So i took a snapshot of what the disk space allocation looked like last time it happened, and today they got a warning again that the disk space was running low.
After investigation, I noticed that each agent (we had 3 agents running) has a **_tool** folder inside their **_work** folder and since we have .NET standard projects in our solution, each agent contained a folder called **dncs** (which I assume are the binaries in order to build said projects.)

So it occurred to me, wouldn't it be possible to copy the **dncs** folder some place else on disk, and add a **symbolic folder link in each agent's _tool** folder to point to the **shared dncs** folder on disk?

I've tried it with 1 agent and it seems to work...
Is there anything I could break with this configuration?
All 3 agents are only used to build our projects, so they all build the same sources

**Comment by juliobbv** [comment]
Hi @dschuermans,

From what I'm able to read, you have three agents configured within the same VM. Is there a reason why you can't just go by using one agent? One agent per machine is the usual configuration -- multiple agents per machine configurations are usually reserved for workloads that individually, are very light on CPU/RAM/disk resources, in order to gain meaningful benefits from running concurrent jobs. Building projects usually don't enter into this category.

In general, we don't recommend sharing any of the agent directories, including the `_tool` folder. The reason is that any jobs that try to mutate on the file/folder contents of the `_tool` folder would cause unpredictable results, which usually manifest in the form of 'file not found' and/or 'file is already in use'. The time spent on debugging these kinds of issues almost always outweighs the space savings from sharing folders.

Thanks,
Julio

**Comment by dschuermans** [comment]
Hey @juliobbv 

Thanks for your response.
The reason why we have 3 agents is that we have integration tests that could potentially run longer than average and we've also set up build validation in PR's
So to avoid being blocked by a longer then usual build by the agent when trying to complete a PR, we decided to have 2 extra agents just in case.

And since the agents all build the same build, we don't risk running into conflicts as you've mentioned.

The agents have been sharing the _tool folder for almost a month now and i'm glad to say we haven't had any issues...

But i'll keep your remarks in the back of my head if we do ever run into issues :)

Thanks!
