### ISSUE TITLE
I'm working through configuring agents on our various servers and adding them to deployment groups.  But I have to install the agent nearly 400 plus servers how could it possible by a powershell script from a tool server which have fire wall access to all those 400 plus servers.

### ISSUE THREAD

**Issue by Prasanthks1400** [microsoft/azure-pipelines-agent#2420]
## Having issue with YAML?
Please log an issue at [Azure-Pipelines-YAML](https://github.com/Microsoft/azure-pipelines-yaml). Over there we discuss YAML templates, samples for Azure Pipelines, and designs for upcoming YAML features. Also a place for the community to share best practices, ideas, and so on. File suggestions and issues here if they're specific to YAML pipelines.

## Having issue with Tasks?
Log an issue at [Azure-Pipelines-Tasks](https://github.com/Microsoft/azure-pipelines-tasks). It contains all of the in-box tasks we ship with Azure-Pipelines/VSTS/TFS. If you're having issues with tasks in Build/Release jobs (e.g. unreasonable task failure) please log an issue there.

## Having issue with software on Hosted Agent?
Log an issue at [Hosted Agent Image Repository](https://github.com/Microsoft/vsts-image-generation). It contains the VM image used in the Azure Pipelines Hosted Agent Pool. If you're having Build/Release failures that seems like they are related to software installed on the Hosted Agent (e.g. the `dotnet` SDK is missing or the Azure SDK is not on the latest version) please log an issue there.

## Having generic issue with Azure-Pipelines/VSTS/TFS?
Please report it on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)

## Have you tried troubleshooting?
[Troubleshooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)

## Agent Version and Platform
Version of your agent? 2.144.0/2.144.1/...

OS of the machine running the agent? OSX/Windows/Linux/...

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server?

If on-premises, which release? 2015.0, 2017.1, 2019 RC2, etc.

If dev.azure.com, what is your organization name? https://dev.azure.com/{organization} or https://{organization}.visualstudio.com

## What's not working?
Please include error messages and screenshots.

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by chshrikh** [comment]
If you go to your deployment group page, you will see the guideline script to in stall the agent. The script can be run remotely.  You can check [this sample](https://github.com/niadak/DGScaleTest/blob/master/AgentConfigurationScript.ps1) as well. 
Using [PowerShell on Target Machines](PowerShell on Target Machines) you can execute this script on your targets. 
Details as per you scenario - 
1) Configure a build agent on a machine which has access to all 400 targets
2) Create a release and add "[PowerShell on Target Machines](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/PowerShellOnTargetMachinesV3#powershell-on-target-machines)" task. Provide the required inputs and execute the provided sample script. ( you may customize it as per your requirement). Ensure you execute this task for group of 25 machines. So for 400 machines you may need to add 16 task.
3) Ensure the script you will write is re-runnable and idempotent, so that in case of failures you can simply re-run the release.

If you are using Azure VMs then you can use [this extension](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deployment-groups/howto-provision-deployment-group-agents?view=azure-devops#install-the-azure-pipelines-agent-azure-vm-extension)

**Comment by chshrikh** [comment]
please let us know if you need any more help here, closing this
