### ISSUE TITLE
References to the "local run" feature still exist

### ISSUE THREAD

**Issue by vtbassmatt** [microsoft/azure-pipelines-agent#2479]
We had considered a local run feature a long time ago. It's not implemented and wouldn't work as originally conceived. Its presence in the agent continues to confuse people, though, and we should delete the dead code.

**Comment by tillik** [comment]
I totally second this @leidegre We run huge templated multistage pipelines here, which are horrendously to debug and any way to run and "debug" them locally would be greatly appreciated. "Download logs" just doesn't cut it.

**Comment by seanvanwyk41** [comment]
I also really want to see this feature, as a devops engineer it is incredibly difficult to test ci/cd changes other than pushing these changes and hoping nothing goes down, or building a full redundant environments which for heavy compute services like AI is expensive. A tool that allows us to get insight into how the different stages execute without needed to wait for an agent and relying on the limited(relative to running it locally) monitoring available in azure devops to detect issues with the pipeline would be incredibly valuable. 

I don't know if this is symptom of how microsoft does their product design but I have noticed in a couple of the products in there suite that they lock users into using the tool the way they assume the users want them to use it instead of giving them the freedom to use them as they like. For example in teams copying text formating into messages making them hard to read in the dark theme and how they limit pinned chats to 15

**Comment by cyberluke** [comment]
The Azure syntax is often misleading. It is worse than XSLT. Expressions / variables / input parameters / quotes / no quotes.

Therefore someone should write some tool to evaluate expressions and check them against predefined Azure variables, at least.

Last time, in a company, my development pipeline hog the agent and whole team was stuck and could not run any deployment because of this online Azure development and validation.

Also AzurePipelines VS Code extension performs only schema validation and Validate button on Azure website does something more - and that is what I need to run locally.

**Comment by mikeblakeuk** [comment]
@vtbassmatt any news on this?

**Comment by vtbassmatt** [comment]
I haven't worked on Azure Pipelines in almost 2 years, so I have no insight into the status of anything.
