### ISSUE TITLE
Agent support for Debian 10 (buster)

### ISSUE THREAD

**Issue by EPinci** [microsoft/azure-pipelines-agent#2497]
## Agent Version and Platform
Running dockerized agent per https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops

## Azure DevOps Type and Version
https://epinci.visualstudio.com

## What's not working?
Please support Debian 10 (buster) now that .NET Core 3.0 supports it.
https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore30

## Agent and Worker's Diagnostic Logs
Debian 10 (buster) doesn't not support libssl 1.0 anymore, just comes with libssl 1.1
Running the agent results in:
```No usable version of the libssl was found```

**Comment by dblock247** [comment]
+1

**Comment by yakeer** [comment]
+1

**Comment by jaworek** [comment]
Are there any plans to support Debian 10 in the near future?

**Comment by Yanal-Yves** [comment]
I have the same issue. On Debian 10 Buster when I execute `./bin/installdependencies.sh`, I am getting the following error:
``` bash
Package libssl1.0.0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libssl1.0.0' has no installation candidate
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libssl1.0.2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libssl1.0.2' has no installation candidate
'apt' failed with exit code '0'
Can't install dotnet core dependencies.
```

Microsoft, do you have any plan to support Debian 10 in the near future ?

**Comment by CompThing** [comment]
There is a pull request with a fixed installdependencies.sh at https://github.com/microsoft/azure-pipelines-agent/pull/2326/
That may lead on to: https://github.com/dotnet/corefx/issues/35838
which has a workaround described on:
https://developercommunity.visualstudio.com/content/problem/752763/is-it-possible-to-install-the-agent-on-raspbian-de.html

**Comment by 0mcandal0** [comment]
Another workaround: install libssl1.0.2 manually from deb package:
```
wget http://ftp.br.debian.org/debian/pool/main/o/openssl1.0/libssl1.0.2_1.0.2s-1~deb9u1_amd64.deb
dpkg -i libssl1.0.2_1.0.2s-1~deb9u1_amd64.deb
```

**Comment by vtbassmatt** [comment]
.NET Core 3.1 support is coming to the agent shortly, then we can evaluate this request.

**Comment by Ezak91** [comment]
@vtbassmatt  some news here?

**Comment by CompThing** [comment]
@Ezak91 I would not hold out much hope of .NET Core 3.1 resolving this issue. The downstream fix was bumped from .NET Core 3.1 to .NET Core 5.0. The fix is now included in the master branch of .NET Core 5.0. A while back, I also tried building the Agent myself using .NET Core 3.1 and it did not help. 
I did manage to find a workaround, which I described on:
https://developercommunity.visualstudio.com/content/problem/752763/is-it-possible-to-install-the-agent-on-raspbian-de.html
I posted as "michael" on Dec 30, 2019 at 09:35 PM
"WORKAROUND for running Agent on Raspbian Buster"

**Comment by vtbassmatt** [comment]
@Ezak91 I'm evaluating our options. We previously had to depend on the (now-legacy) libcurl version of the HTTP libraries. I've got feature on the backlog to break that dependency since the native HTTP library appears to be better-baked in 3.1. _If_ that's the dependency that's dragging along libcurl, then it would be a fix. But if some other part of .NET requires libssl, then I can't fix it until they do 😞
