### ISSUE TITLE
Remove string-typing from plugin loader

### ISSUE THREAD

**Issue by vtbassmatt** [microsoft/azure-pipelines-agent#2669]
Fix [this](https://github.com/microsoft/azure-pipelines-agent/blob/0533383fe43ae079cd1d8f38342bbd465e7c2c4e/src/Agent.Worker/AgentPluginManager.cs#L33). This will unblock the use of static analysis tools and help prevent runtime issues.

**Comment by jtpetty** [comment]
[this](https://github.com/microsoft/azure-pipelines-agent/blob/0533383fe43ae079cd1d8f38342bbd465e7c2c4e/src/Microsoft.VisualStudio.Services.Agent/ExtensionManager.cs) also needs to be addressed

**Comment by jtpetty** [comment]
We attempted to fix this with PR #2701 
That worked in unit tests, but failed when actually running the agent and was reverted with PR #2727 

@vtbassmatt - Do you think it is still worth doing this work?

**Comment by vtbassmatt** [comment]
Don't we need this for static analysis to work properly? I'm agnostic on the value of this in a vacuum, but adding static analysis seemed to be paying off in terms of quality.

**Comment by jtpetty** [comment]
We are running static analysis now and it is fine. What this is preventing is accurate dead code analysis. I am not sure my previous attempt would have solved that problem either, since I was dynamically discovering the classes. I am fine if we still want to think about this more and try to come up with a more elegant solution.

**Comment by vtbassmatt** [comment]
Gotcha. Since it's primarily an engineering concern and I'm supposed to be doing less dev/more product, I'll defer to @mjroghelia
