### ISSUE TITLE
Releases in Github are still incorrectly marked as pre-release

### ISSUE THREAD

**Issue by giggio** [microsoft/azure-pipelines-agent#2688]
As I can't reopen #2521, I am opening this again, as the problem is still happening.

Some of your [releases](https://github.com/microsoft/azure-pipelines-agent/releases) are incorrectly marked as pre-releases. Right now `2.163.1`, `2.163.0`, and others are marked as pre releases, and I'm assuming they are not pre releases as per semver.

On #2521 it was mentioned that marking the release as not pre release was a manual step, and it seems this process has not yet been fixed. Maybe automating it could help?

Please fix this, as we are watching the releases and this is reporting incorrectly.

**Comment by jtpetty** [comment]
2.163.0 is a pre-release, it was never rolled out to customers. 2.163.1 is a rerelease of 2.160.1 to work around a bug that was introduced after 2.160.1. I have fixed the page to reflect that 2.163.1 is no longer a pre-release. 2.163.2 is also a pre-release and will not be rolled out to customers.

**Comment by giggio** [comment]
Would it be possible to use [semver](https://semver.org/) for the releases, to more accurately describe them?

**Comment by EmFl** [comment]
Hello,
I'm seeing 2.164.8 as a prerelease on github and this is I guess confirmed by the fact that calling _apis/distributedtask/packages/agent?platform=linux-x64 doesn't list 2.164.8 version. So when I build my docker image, it installs 2.164.7, however, when my agent starts, it gets updated with 2.164.8...

**Comment by jtpetty** [comment]
We are currently rolling out 2.164.8 and it has not gone out to all customers yet. Once it is completely rolled out, it will be marked as 'released'. We are working on a better way to communicate the agent version rollout, but unfortunately GitHub only gives us two states to work with, Pre-Release and !Pre-Release. This makes our use case a little difficult since we roll out the agent to customers over several days to attempt to minimize impact.

**Comment by giggio** [comment]
How about using semver as per the example for `2.163.0`?
