### ISSUE TITLE
[Git source provider] Add ability to pull git repos without tags, or give a custom fetch command

### ISSUE THREAD

**Issue by dany74q** [microsoft/azure-pipelines-agent#2713]
[Posted on Developer Community](https://developercommunity.visualstudio.com/idea/878730/git-source-provider-add-ability-to-pull-git-repos.html) as well.

It would be very beneficial (at least for our use case) to override the default git fetch command, so it would not fetch any tags during git fetch (i.e. running fetch w/ --no-tags)

In our very specific scenario (and others may be in a similar boat), we have a very large monorepo with auto-created tags from our previous CI solution (to be exact, we have 309k tags)

We found that, locally, fetching our repository with --no-tags, dramatically affects fetch performance (3 minutes -> 30 seconds ~)

Currently, we can either have a shallow clone with a given depth (which didn't improve performance that much, sadly) or not sync sources altogether;
With the latter, one needs to add a custom task that would fetch the sources with the given git credentials, which is a bit cumbersome and could be easily abstracted away by the git source provider.

I'd love to contribute the functionality myself, if needed, and I wanted to hear your feedback about the direction in which one should go about - 

1. Add a specific 'No tags' option to the various git plugins, source provider and cli manager
2. Add the ability to provide a custom fetch command in case don't sync sources is selected (would probably need to add some shell sanitization here to ensure the given command isn't evil)

Thanks !

**Comment by jtpetty** [comment]
@vtbassmatt - Do you know if we already have a way to do this or are planning to add one?

**Comment by vtbassmatt** [comment]
Not something we're planning to do, though I can see why you'd like to shave the time on your clone! This worked for me and isn't too clunky:
```yaml
steps:
- checkout: none
- script: |
    git clone -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" $(Build.Repository.Uri) s
  displayName: Checkout the repo
```

This clones the repo into the `s` directory just like the default checkout step would.

Since you opened a feature request on Developer Community, I'll go ahead and close this one for sanity and tracking reasons :grin:

**Comment by dany74q** [comment]
Thanks @vtbassmatt ! 

This does solve the issue in most cases, however, when using internal tools (a-la CDPx) - we can't run such a step due to network unavailability.

**Comment by vtbassmatt** [comment]
The source provider runs in essentially the same way as the rest of your pipeline. I know that CDPx plays some games with what tasks are allowed, where they run, etc. so that may not be strictly true in your case. But CDPx is also being replaced with YAML templates once my team finishes some other work, so hopefully it won't be a blocker for long.
