### ISSUE TITLE
Agent change (v2.163.1-v2.164.6) causes reconstruction of workspace

### ISSUE THREAD

**Issue by compnerd** [microsoft/azure-pipelines-agent#2761]
## Having issue with YAML?
Please log an issue at [Azure-Pipelines-YAML](https://github.com/Microsoft/azure-pipelines-yaml). Over there we discuss YAML templates, samples for Azure Pipelines, and designs for upcoming YAML features. Also a place for the community to share best practices, ideas, and so on. File suggestions and issues here if they're specific to YAML pipelines.

## Having issue with Tasks?
Log an issue at [Azure-Pipelines-Tasks](https://github.com/Microsoft/azure-pipelines-tasks). It contains all of the in-box tasks we ship with Azure-Pipelines/VSTS/TFS. If you're having issues with tasks in Build/Release jobs (e.g. unreasonable task failure) please log an issue there.

## Having issue with software on Hosted Agent?
Log an issue at [Hosted Agent Image Repository](https://github.com/Microsoft/vsts-image-generation). It contains the VM image used in the Azure Pipelines Hosted Agent Pool. If you're having Build/Release failures that seems like they are related to software installed on the Hosted Agent (e.g. the `dotnet` SDK is missing or the Azure SDK is not on the latest version) please log an issue there.

## Having generic issue with Azure-Pipelines/VSTS/TFS?
Please report it on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)

## Have you tried troubleshooting?
[Troubleshooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)

## Agent Version and Platform
Version of your agent? 2.164.6

OS of the machine running the agent? Windows/Linux

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server?
Azure Pipelines (dev.azure.com)

If on-premises, which release? 2015.0, 2017.1, 2019 RC2, etc.

If dev.azure.com, what is your organization name? https://dev.azure.com/{organization} or https://{organization}.visualstudio.com

https://compnerd.visualstudio.com / https://dev.azure.com/compnerd

## What's not working?
Please include error messages and screenshots.

Something changed between v 2.163.1 and v 2.164.6.  The agent has been bumping workspace IDs on each build continuously without cleaning up the previous content.  This is leading to constant disk space exhaustion.

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by jtpetty** [comment]
@compnerd - Can you send us some of the agent and worker logs from the hosts that you are seeing this issue?

**Comment by jpricket** [comment]
It would also be great if you could produce a minimal repro yaml file that we could try locally.

**Comment by compnerd** [comment]
@jtpetty sure, I've attached them here.
[Agent_20200129-055130-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/4129276/Agent_20200129-055130-utc.log)
[Worker_20200129-161343-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/4129277/Worker_20200129-161343-utc.log)

@jpricket - not sure about a minimal repro, my build setup is *extremely* complicated (perhaps not very idiomatic either).  https://github.com/compnerd/swift-build/blob/master/.ci/vs2017-facebook.yml is likely the smallest one which is known to reproduce the issue - but its heavily templated.

BTW, if there are suggestions you have on how to organize the pipeline into something better, please let me know.  Also, if there are tests that you want me to run as one offs, I should be able to trigger those (e.g. if altering the structure somehow impacts the behavior of the agent).

**Comment by compnerd** [comment]
In the meantime, is there a way to mitigate the issue by forcing a cleanup of the old workspace?  Note that this still is a significant cost: build times doubled due to invalidation of the caching.

**Comment by drodriguez** [comment]
So what we found out.

In a multi-stage, multi-repo setup, if two stages checkout different sets of repositories, both stages seems to use the same `collectionId`/`definitionId` pair.

When the multi-repo improvements were introduced the code that calculates the hash uses the repositories that are actually checked out as part of the hash to determine if the work directory should be reused or not (before only `self` was used, I think). Since two stages checkout different repo sets, the second one will discard the first stage work directory, and a new build first stage will discard the second stage work directory.

The result is that the work directories are not reused, and they are all the time selected for garbage collection. If the repos are big enough, this might mean that the disk space is filled with discarded work directories before maintenance happens.

A setup that should reproduce it will be something like this:

```
resources:
  repositories:
    - repository: foo/bar
      type: github
      name: foo/bar
      endpoint: GitHub
    - repository: foo/baz
      type: github
      name: foo/baz
      endpoint: GitHub
stages:
  - stage: stage1
    jobs:
      - job: job1
        steps:
          - checkout: foo/bar
  - stage: stage2
    jobs:
      - job: job2
        steps:
          - checkout: foo/baz
```

(I haven't actually tested that setup, so the syntax might be off, but it should give you an idea of the real setup)

The workaround is checking the same set of repos in both stages. That makes the hash of both stages match, and the work directory is not discarded.

The solution for multi-stage pipelines should be having the stage ID (if that exists) as part of the source mappings and the hash calculations, so each stage might potentially require a different work directory, but each stage will receive one, and not try to reuse the previous stage ones. Another solution might be doing the hash with the list of repositories in resources, not only the ones that happen to be checkout during the stage.

I don't know if in the case of slightly different jobs the same problem will reproduce (imagine that one job checkout one repo, and another job checkouts a different repo), but seems possible.

**Comment by jpricket** [comment]
That's some great information. That makes perfect sense. We need to be more careful about computing the hash in these types of cases. 
Thanks for following up and providing the workaround in case others run into this.
It will take some time to create and test the solution, so a workaround is definitely a must.

**Comment by compnerd** [comment]
@jpricket any update on this getting resolved?

**Comment by jpricket** [comment]
@compnerd - We did put a fix into the agent back in February, but I don't think the feature flag was ever turned on.
@mjroghelia - the FF is passed to the agent as variable "agent.useWorkspaceIds". I don't know the name of the server FF. Can you check to see which flag it is and if it ever got turned on? 

To test this @compnerd, you can probably add a variable with the same name (agent.useWorkspaceIds) to the pipeline and set it to "true".

**Comment by mjroghelia** [comment]
@jpricket @compnerd Sorry, I neglected to roll out the feature flag. I will start that now.

**Comment by mjroghelia** [comment]
@compnerd This fix has fully rolled out. Agent version 2.168.2 or later should address the issue. Can you confirm?

**Comment by aok-foss** [comment]
Updating the feature flag seems to have caused an issue with our cleanup jobs. Please see #3073.

**Comment by compnerd** [comment]
I believe that the change was rolled back, so I haven't tested it yet.  It would be very helpful since I think that the cloning step takes about 10 minutes on many of the stages that is unnecessary.

**Comment by aok-foss** [comment]
Not stale. The fix in the issue has been reverted; there's no evidence of it having been applied again.

**Comment by mjroghelia** [comment]
The fix was reapplied after fixing the related issue with maintenance jobs. This should be resolved.
