### ISSUE TITLE
##[error]A potentially dangerous Request.Path value was detected from the client (:).

### ISSUE THREAD

**Issue by ShadowXVII** [microsoft/azure-pipelines-agent#2877]
When using `##vso[task.setvariable variable=variableName;]$myVarValue`, my value has a semicolon in it i.e. $myVarValue = "test:value".

However, I get the following error in the pipeline `##[error]A potentially dangerous Request.Path value was detected from the client (:).` which suggests it's getting blocked?

Is there a way to escape this?

## Agent Version and Platform
2.160.0 - Windows Server 2019

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com)

**Comment by ShadowXVII** [comment]
I escaped the value with a backtick `.Replace(':', '`:')` before passing it into `task.setvariable` and that seems to work. 

Somehow the backtick didn't make it into the variable value, but referencing it later doesn't have a backtick.

Unless the agent updated overnight with a fix ;)

**Comment by ShadowXVII** [comment]
🐞

**Comment by tannerwatson** [comment]
I hit the same issue today when trying to use the [AddBuildTag](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#addbuildtag-add-a-tag-to-the-build) logging command with a tag that contained `:`.

The docs don't mention restricted characters so I created MicrosoftDocs/azure-devops-docs#9371

**Comment by vtbassmatt** [comment]
I can't repro this.

My pipeline:
<img width="480" alt="image" src="https://user-images.githubusercontent.com/714283/103672001-ac7cd080-4f49-11eb-8e8d-ef2d3b6b49c1.png">

Results:
<img width="513" alt="image" src="https://user-images.githubusercontent.com/714283/103672043-b8689280-4f49-11eb-9f2c-8263ffcf4a96.png">

**Comment by ShadowXVII** [comment]
Hmm. I know both generate PowerShell scripts but we're using a script file vs. inline script.

Or, maybe this is fixed in a recent version. Will need to do some testing.

**Comment by jagunter** [comment]
Ran into the same issue described by @tannerwatson while trying to add a build tag which contained a `:` using an inline powershell script:

```
Write-Host "##vso[build.addbuildtag]InternalJobId:$job_id"
```

However, the step failed:

```
##[debug]Tagging pipeline run with job id: 2cf4316c-85c1-4832-8a47-3da884fa33b8


Async Command Start: Add Build Tag
Async Command End: Add Build Tag
##[error]A potentially dangerous Request.Path value was detected from the client (:).
```

**Comment by lukemaslany-next** [comment]
Hello, all.

I've just tripped over the same issue when trying to set a build tag in a pipeline using an inline bash task, where the tag contains a semi-colon.

My command is:
```
last_scanned="last_scanned:$(date --utc --iso-8601=seconds)"
echo "##vso[build.addbuildtag]$last_scanned"
```

The error is:
```
Async Command Start: Add Build Tag
Async Command End: Add Build Tag
##[error]A potentially dangerous Request.Path value was detected from the client (:).
```

Does anyone have an example of this working in a pipeline?  I'd happily take either Bash or PowerShell at this stage...

I'm currently running agent version `2.210.1` on a runner image using `ubuntu-20.04`.

**Comment by MrOwen** [comment]
For all who come across this issue, here was my workaround:

* `$pipelineTags` is an array of strings representing the tags you wish to add. Populate this variable however you see fit.
* Ensure that your pipeline is granted API access and that the access token is passed into the script: https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#systemaccesstoken

```powershell
$headersMain = @{
  Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"
}
$adoApiTagUri = "$($env:SYSTEM_COLLECTIONURI)$($env:SYSTEM_TEAMPROJECTID)/_apis/build/builds/$($env:BUILD_BUILDID)/tags?api-version=6.0"

Write-Host "Tags to add to pipeline run:`n  $($pipelineTags -join "`n  ")`n"
Invoke-RestMethod -Uri $adoApiTagUri -Headers $headersMain -Method Post -ContentType 'application/json;charset=utf-8' -Body $(ConvertTo-Json -InputObject $pipelineTags -Compress)
```

`ConvertTo-Json -InputObject` is required, piping does not seem to work for arrays with length == 1.

**Comment by lukemaslany-next** [comment]
@MrOwen I ended up with a similar workaround.  I constructed the JSON payload for my API call directly, rather than using the ConvertTo-Json.  Your solution does looks cleaner though, so I think I'll adopt that moving forwards.  :)

Interestingly the API documentation ([Tags - Add Build Tag](https://learn.microsoft.com/en-us/rest/api/azure/devops/build/tags/add-build-tag?view=azure-devops-rest-6.0)) stated to use the PUT method - but that failed when I tried, so instead I used a PATCH (which is what the web console appeared to use) and that works as expected.

I note though your own solution uses the POST method.

I find it somewhat ironic the documentation states to use PUT, but it only works if we use the PATCH or POST methods instead.

Personally I feel this should be treated as a bug with `##vso[build.addbuildtag]`, so I opened a feedback case: [Error when setting ##vso[build.addbuildtag] containing a colon](https://developercommunity.visualstudio.com/t/Error-when-setting-vsobuildaddbuildt/10163239)

**Comment by efthimisxen** [comment]
Hello,

I came through the same bug. I am trying to run a job in my pipeline with `##vso[build.addbuildtag]env:test`. I can't avoid the special character ":" as this format is the needed in order to send the metadata in another integration.

Is there any solution yet? I would not like the workaround mentioned above.
Thank you.

**Comment by hbarajas** [comment]
Having the same problem, can anyone point me to the right direction, I need the character ":" , any solution?

**Comment by ogimgio** [comment]
also same problem..

**Comment by yoshivda** [comment]
Same problem, but the issue is still marked as completed :(
