### ISSUE TITLE
How to disable `##[error]` for output messages.

### ISSUE THREAD

**Issue by seanyen** [microsoft/azure-pipelines-agent#2942]
## Agent Version and Platform
Version of your agent? 2.166.3

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com

## What's not working?
I have a self-hosted agent registered to my `dev.azure.com` organization, and when I run my pipeline, some output messages seem to be interpreted as `##[error]`. However when I run the same pipeline with Microsoft-hosted agent I never saw this behavior. Any settings to opt-out this behavior?

![image](https://user-images.githubusercontent.com/25241284/80140774-50118680-855d-11ea-98d2-d8ba7d5826f2.png)

**Comment by chenbojian** [comment]
It looks like your issue is similar to the issue I am facing but a little different. In my case, I am running native command using powershell task. It give me error when stderr was writed. 

The issue I have only happens on windows-2019. The vs2017-win2016 images works fine.

I posted a comment here https://github.com/microsoft/azure-pipelines-agent/issues/2860 , which is more related.
