### ISSUE TITLE
JDK capability is not automatically detected on on-prem agent

### ISSUE THREAD

**Issue by anton-erofeev** [microsoft/azure-pipelines-agent#3011]
## Agent Version and Platform
Version of your agent? 2.163.1

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com

If dev.azure.com, what is your organization name? https://dev.azure.com/v-anero1

## What's not working?
If I run a task that requires JDK (such as Android Signing, etc) on a self-hosted agent that has JDK, but the JAVA_HOME environment variable is not set, it throws an error: `No agent found in pool self-hosted-win which satisfies the specified demands: JDK` 
Is it possible to fix it? For example to search for JDK even if JAVA_HOME is not set?

Related issue: https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1722324

## Agent and Worker's Diagnostic Logs
##[error]No agent found in pool self-hosted-win which satisfies the specified demands: JDK, Agent.Version -gtVersion 2.163.1

**Comment by martys** [comment]
any updates on this ? have the same issue :(

**Comment by anatolybolshakov** [comment]
Hi @martys @anton-erofeev current capability scanning process relies on checking of predefined set of environment variables - so setting up of 'JAVA_HOME' environment variable should help to resolve this issue.
@martys does this help to resolve the issue you faced with?

**Comment by martys** [comment]
I guess. 
The question is more like - how come there is a manuall process involved in this in 2021.
As a user I would expect that after I unstall the JDK, all the rest would happen automatically, without me reading some manualls, and setting up some variables somewhere.. 
(as a programer I totally understand You, and it's not a big issue once You know what it is. Although it's just anoying to spend a couple of hours hunting around, why is stuff not working (especially with the build, where each try, takes at least a couple of minutes) and after having wasted half a day arrive at a simple env_variable issue.

So my hope is, this could be improved somehow, in order to save fellow developers from having to spend half a day hunting around for issues in the log files.

Bests, 
Marty

**Comment by anatolybolshakov** [comment]
Hi @anton-erofeev @martys we merged related [PR](https://github.com/microsoft/azure-pipelines-agent/pull/3381) with a fix - so it will be available with the next agent release.

**Comment by martys** [comment]
Thanks @anatolybolshakov 
Happy to hear this was fixed.

**Comment by anatolybolshakov** [comment]
Hi @martys we rolled out related changes - I'm closing this at the moment - please let us know if you have any other issues.
