### ISSUE TITLE
Download Pipeline Artifact reports that drop/Linux_Phase is not a valid artifact names

### ISSUE THREAD

**Issue by VladimirKhvostov** [microsoft/azure-pipelines-agent#3034]
Download Pipeline Artifact task reports that "drop/Linux_Phase" is not a valid artifact name, which is not correct.
Artifact names can contain / for sure. I can download such drop using the following command:

az pipelines runs artifact download --artifact-name 'drop/Linux_Phase' --path c:\tmp\drop2 --run-id 32568578

The bug is here: https://github.com/microsoft/azure-pipelines-agent/blob/5e79b331809d8074ba6d7be4d3b9cad18a75c115/src/Agent.Plugins/PipelineArtifact/PipelineArtifactPluginUtil.cs#L21

**Comment by mjroghelia** [comment]
@johnterickson Do you have any context for this restriction?

**Comment by johnterickson** [comment]
IIRC this was intentional to avoid the buggy behavior of Build Artifacts.

In Build Artifacts, a command line `az pipelines runs artifact download --artifact-name 'drop/Linux_Phase' --path c:\tmp\drop2 --run-id 32568578` could mean either download the contents of:
1. An artifact published with the name "drop/Linux_Phase" with a file at "file.txt" with the contents "good".
2. An artifact published with the name "drop" with a file at "Linux_Phase/file.txt" with the contents "evil".

Assuming I am recalling the above correctly, we should probably add a message explaining this in PIpeline Artifacts.
