### ISSUE TITLE
Use a more efficient compression method in the pipeline-cache

### ISSUE THREAD

**Issue by aminya** [microsoft/azure-pipelines-agent#3109]
Currently, [PipelineCache uses `tar` for compression](https://github.com/microsoft/azure-pipelines-agent/blob/c0e90fadee6568832ee67b8e6745793527e8c0bb/src/Agent.Plugins/PipelineCache/TarUtils.cs#L19). However, `tar` does not compress the file efficiently (almost 0), while it still takes some time to make a `tar` archive. 

Based on my experience, the performance bottleneck of the current cache method is in the time it takes to "download" or "upload" the files. By using some level of compression such as 7z on the fastest mode, we can compress the cache and so reduce the time it takes on uploading and restoration.

For example, consider this `node_modules` caching. Most of this 1 min and 15 seconds is spent on "downloading" a 450 MB `node_modules` folder. While this folder's size will reduce significantly if "some level" of compression is applied.

```
2020-09-16T02:27:00.6020410Z Downloaded 0.0 MB out of 448.8 MB (0%).
2020-09-16T02:27:05.6109630Z Downloaded 70.7 MB out of 448.8 MB (16%).
2020-09-16T02:27:10.6170160Z Downloaded 106.8 MB out of 448.8 MB (24%).
2020-09-16T02:27:15.6130300Z Downloaded 122.1 MB out of 448.8 MB (27%).
2020-09-16T02:27:20.6134750Z Downloaded 122.1 MB out of 448.8 MB (27%).
2020-09-16T02:27:25.6143500Z Downloaded 122.1 MB out of 448.8 MB (27%).
2020-09-16T02:27:30.6148110Z Downloaded 122.1 MB out of 448.8 MB (27%).
2020-09-16T02:27:35.6152000Z Downloaded 122.1 MB out of 448.8 MB (27%).
2020-09-16T02:27:40.6154770Z Downloaded 122.1 MB out of 448.8 MB (27%).
2020-09-16T02:27:45.6800460Z Downloaded 125.4 MB out of 448.8 MB (28%).
2020-09-16T02:27:50.7042480Z Downloaded 162.5 MB out of 448.8 MB (36%).
2020-09-16T02:27:55.7103940Z Downloaded 202.6 MB out of 448.8 MB (45%).
2020-09-16T02:28:00.8151660Z Downloaded 265.0 MB out of 448.8 MB (59%).
2020-09-16T02:28:05.8179650Z Downloaded 380.2 MB out of 448.8 MB (85%).
2020-09-16T02:28:10.8267250Z Downloaded 417.8 MB out of 448.8 MB (93%).
2020-09-16T02:28:12.2241480Z Downloaded 448.8 MB out of 448.8 MB (100%).
```

[Another example](https://dev.azure.com/atomcommunity/atomcommunity/_build/results?buildId=834&view=logs&j=9e553d4d-6360-5a42-fcf6-9ca3e737bdc9&t=1edb61e8-f066-5906-7a74-1a0f51dc918e)

Here is a little benchmark I did for the compression/time of [the bootstrapped Atom repository](https://github.com/atom/atom):
```
1.74 GB

7zip 
-----
ultra 2:19 494MB
maximum 1:52 511MB
normal 1:12 528MB
fast 0:40 604MB
fastest 0:32 658MB

tar
----
tar 0:15 1.74 GB
```

As you see, by only spending 15s more, we can reduce the size from 1.74GB to 685MB!

**Comment by OranguTech** [comment]
Point of technical clarification that most everyone already knows: While this is probably a good enhancement, note that (AFAIK) tar doesn't have any compression capabilities itself. Depending on environment/version, having it pipe through gzip would be the "standard" method. IDK what is required to have it use a high-speed/lower compression flag.

**Comment by DeeDeeG** [comment]
I think the bottleneck is mostly compression/decompression time.

---

Thoughts on optimizing compression/decompression time:

_(That can be optimized, too. Check out [Fedora's recent look at compression performance](https://fedoraproject.org/wiki/Changes/Switch_RPMs_to_zstd_compression) as a case study. Zstd is really fast and space-efficient. Some benchmarks from other sources: [[1](https://github.com/inikep/lzbench#benchmarks)] and [[2](https://linuxreviews.org/Comparison_of_Compression_Algorithms)]. Other than Zstd, LZ4 is interesting as it is way way fast to compress and decompress, but not as space-efficient.)_

_(I don't know how those FLOSS algorithms compare to 7z, but maybe the compression is arguably **too aggressive** and becoming severely CPU-bound rather than lightly network-bound? Worth a thought, especially if this might ultimately be LAN network usage within the same datacenter. Which is more precious, the network bandwidth or the CPU time?)_

---

Evidence that we're waiting on compression/decompression time more than the network: 

#### Decompression

<details><summary>Screenshot of "Enable system diagnostics" checkbox (click to expand)</summary>

![Azure Pipelines, starting a new run for a pipeline with the "Enable system diagnostics" checkbox checked](https://user-images.githubusercontent.com/20157115/105218718-7df31e00-5b23-11eb-8aa1-5fbd062f6e4b.png)

</details>

_(To reproduce these results, manually run a pipeline with the "[x] Enable system diagnostics" checkbox checked, and during cache restore you will see a lot of lines like this:`x [path]`. I assume this means the `tar x` command, for "extract".)_

You can see the download progress lines are printed sandwiched in-between all of the extracting that is going on. https://dev.azure.com/DeeDeeG/b/_build/results?buildId=1009&view=logs&j=0c24d9d5-0e27-5404-37e0-91cb4d692d0c&t=ef37c6e4-1fe1-524c-2b36-45447b74650f&l=5779

Extraction apparently takes a ton of time, downloading maybe not so much.

#### Compression

I think compression takes a while, too. Here's a bunch of lines `a [path]` (I assume the "a" stands for "add"?).
https://dev.azure.com/DeeDeeG/b/_build/results?buildId=1009&view=logs&j=e2cf4b02-5697-54ad-cf7c-fc2a840d53af&t=7a5bb1d7-ddca-4fd6-90f8-e03a82bd0170&l=57610

_(I was not watching closely which part took more time, adding files or uploading. If I ran again, I would try to look more closely. But anyone reading this with a pipeline using the cache@V2 task can try it out and see for themselves.)_

**Comment by DeeDeeG** [comment]
@OranguTech is right that `tar` is usually used with any of a large variety of compression algorithms, popularly `gzip` or `xz`.

To compress with xz algorithm: `tar cJf out.tar.xz [path_to_compress]` (`J` shortflag is for xz)
To compress with gzip algorithm: `tar czf out.tar.gzip [path_to_compress]` (`z` shortflag is for gzip)

**Comment by aminya** [comment]
> I am confident Azure Pipelines caching already uses some decent compression. There is a reasonable possibility that it could be tuned better though, see comment above.

As I add the link to the original post, it just [uses Tar](https://github.com/microsoft/azure-pipelines-agent/blob/c0e90fadee6568832ee67b8e6745793527e8c0bb/src/Agent.Plugins/PipelineCache/TarUtils.cs#L19) which just **wastes** time and has no compression.

**Comment by DeeDeeG** [comment]
But what about these statistics printed during the cache restore?

```
Download statistics:
Total Content: 482.9 MB
Physical Content Downloaded: 157.1 MB
Compression Saved: 325.7 MB
Local Caching Saved: 0.0 MB
Chunks Downloaded: 5,548
Nodes Downloaded: 11
```

The physical size downloaded is smaller than the actual content... About 1.5/5 (calculator says this is a bit under a third) of the original size.

Yes tar _can_ make archives that aren't compressed. But it can makes compressed ones, and almost nobody uses tar without compression... Just because the word tar is involved, that doesn't mean it's being run with no compression.

Maybe there is better compression tuning that is possible. But I believe it is already compressed.

**Comment by DeeDeeG** [comment]
Also it's not believable that the download takes minutes, but decompression takes zero seconds. The "download progress lines" are printed during the decompression task.

So I think the output for the cache task is misleading. It makes it look like the download is slow, but you're really seeing how long downloading and decompressing takes, combined.

**Comment by emitrackman** [comment]
Is there a way to manually specify the compressor's command line for given cache task?

**Comment by johnterickson** [comment]
FYI we do compression "under the hood" as part of our deduplication.

**Comment by clemlesne** [comment]
Totally agree. It'll save numerous CPU and netwok!
