### ISSUE TITLE
Feature Request: Ability to define service name

### ISSUE THREAD

**Issue by JasonWhall** [microsoft/azure-pipelines-agent#3144]
This is a request to add the ability to customise the service name that is used when installing the DevOps agent as a service. The requirement for this is to allow the user installing to specify a known name at the point of install, this then allows configuration management to be used to automate the installation and managing the service (e.g puppet). 

Currently the service names are pre-determined based on other inputs (org name, agent name, pool name) and are truncated which does allow for some predetermination however this is also made worse on systemd based systems by that it also [escapes special characters in the name](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Misc/layoutbin/systemd.svc.sh.template#L3) before installing it. 

This makes it extremely difficult to predetermine the name to use in something like  puppet where you have to specify the service name:
```
service {"Agent-Service":
   name     => 'Agent-Service-Name',
    ensure  => 'running',
}
```

It would be good to have the ability to pass an additional flag when calling the `svc.sh install` command with a parameter called `--service-name` to override the prepopulated one. This should be optional and explain that it should be constrained to the character limitations of the system you are installing it on.

This request is primarily aimed at the Linux installer but may also be beneficial for Windows/Mac as well.

This would help bring puppet modules like this - https://github.com/JacobHenner/puppet-azure_pipelines back into valid usage.

Slightly Related issue #2738

**Comment by margani** [comment]
This issue is still relevant and unresolved.

The inability to explicitly set the service name when installing the DevOps agent continues to make configuration management tools (e.g. Puppet) difficult or impractical to use, especially on systemd-based Linux systems where service names are escaped and truncated.

Being able to pass a --service-name flag during svc.sh install would still be very valuable and would restore compatibility with existing automation modules.
