### ISSUE TITLE
git fetch doesn't respect branch filters

### ISSUE THREAD

**Issue by genne** [microsoft/azure-pipelines-agent#3160]
## Agent Version and Platform
Current agent version: '2.177.0'
OS of the machine running the agent? Ubuntu

## Azure DevOps Type and Version
dev.azure.com

If dev.azure.com, what is your organization name? https://dev.azure.com/join-trine/Trine

## What's not working?
Before this version git fetch locked like this:
```
git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=50 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/6014/merge:refs/remotes/pull/6014/merge
```

With this version it looks like this:
```
git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=50 origin +4d3d95f3be63fdca5a3951217aa9bf2e58dbdc2f:refs/remotes/origin/4d3d95f3be63fdca5a3951217aa9bf2e58dbdc2f
```

I.e. the list of branches has changed. This causes build errors for us, since we rely on some specific branches being available.

**Comment by genne** [comment]
Workaround seems to be to set `VSTS.DisableFetchByCommit: true`.

**Comment by jeschu1** [comment]
We updated the GitHub behavior to match Azure Devops which does a checkout by commit.  
Checkout by commit is more specific since the branch can change between builds.

**3 options to workaround:**
1. `VSTS.DisableFetchByCommit: true` gives you the old behavior
2. Add the specific fetch via a different step in your build
3. Change your downstream behavior to be commit, instead of branch specfic
