### ISSUE TITLE
Alternate Agent runsvc asks for node6

### ISSUE THREAD

**Issue by resried** [microsoft/azure-pipelines-agent#3250]
## Agent Version and Platform
Version of your agent? pipelines-agent 2.180.1 

OS of the machine running the agent? Linux

Variant: Pipelines-agent (no node6)

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server? dev.azure.com

If dev.azure.com, what is your organization name? swisslife

## What's not working?
On Linux Agent cannot be started as a service. 
The runsvc.sh is triing to call externals/node/bin/node - but in the pipelines-agent this is no more existing (only node10 exists, node was node6). 

## Agent and Worker's Diagnostic Logs

Feb 08 16:09:50 EPDL4402 systemd[1]: Started Azure Pipelines Agent (swisslife.P_VWS.epdl4402_1).
Feb 08 16:09:50 EPDL4402 runsvc.sh[7987]: .path=/home/vwst/.local/bin:/home/vwst/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/ho…otnet/tools
Feb 08 16:09:50 EPDL4402 runsvc.sh[7987]: /apps/vws/ado/agent_1/runsvc.sh: line 16: ./externals/node/bin/node: No such file or directory
Feb 08 16:09:50 EPDL4402 systemd[1]: vsts.agent.swisslife.P_VWS.epdl4402_1.service: Main process exited, code=exited, status=127/n/a
Feb 08 16:09:50 EPDL4402 systemd[1]: vsts.agent.swisslife.P_VWS.epdl4402_1.service: Failed with result 'exit-code'.

**Comment by max-zaytsev** [comment]
Hi @resried, Could you please update the agent to a newer version and try again?

**Comment by Chefkoch81** [comment]
I have the same issue and just tried it with v2.181.2, which is the newest available right now.

**Comment by resried** [comment]
@Chefkoch81 
As a workaround you can edit manually bin/runsvc.sh and switch in there from node to node10.
Didn't help me, since the docker-Plugin is still using node6, but maybe it helps you.

**Comment by Chefkoch81** [comment]
> @Chefkoch81
> As a workaround you can edit manually bin/runsvc.sh and switch in there from node to node10.
> Didn't help me, since the docker-Plugin is still using node6, but maybe it helps you.

I did just that and it works. Thank you!

Since you are mentioning the docker plugin and the necessity for node6, thats a dealbreaker. Too bad, going to revert.

IT is all over me because of automated scans find node6 (which is EOL) and I need to remove it. EOL software is not allowed here in general.

**Comment by mjroghelia** [comment]
@max-zaytsev For context, we have started publishing alternate packages of the agent that don't include Node 6. See [these notes](https://github.com/microsoft/azure-pipelines-agent/blob/v2.181.2/docs/node6.md). [This script](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Misc/layoutbin/runsvc.sh#L16) needs to be updated to use `node10` instead of `node` in the externals directory, and be tested to ensure it still works.
