### ISSUE TITLE
Agent should not include PATH as a capability

### ISSUE THREAD

**Issue by simonsabin** [microsoft/azure-pipelines-agent#3367]
## Whats not working
The agent at startup of the agent reads the environment variables and puts them as capabilities. 
At runtime of a pipeline these stored values are uses to set the environment variables, irrespective of what is currently set for the user/machine. 

This means that if you use the agent to install anything that sets an environment variable, PATH being the most common. Then the agent doesn't pick up the change to the environment variable and subsequent tasks don't have the current values. 

This is really an issue for persistent agents used for deployments i.e. in environments/deployment groups, but also can be an issue for pipelines that install tools. 

## Workarounds
At the start of the pipeline you can overwrite the path variable and then export it, so future tasks get the values. 
For subsequent jobs that requires passing the output to those jobs. This is super messy. 

## Proposed solution
1. A means to get the agent to update capabilities within the pipeline.  
2. Allow environment variables to be loaded from the machine, rather than from capabilities.

This is related to #3228 which was causing the same issue.

**Comment by anatolybolshakov** [comment]
Hi @simonsabin 
For the first - I would suggest to create a ticket on https://developercommunity.visualstudio.com/search?space=21 - since it would require some changes in whole process - how tasks are selected for execution according to demands (since capabilities will no longer be static during pipeline execution).
for the second one - I don't think that there is a cross-platform solution to retrieve environment variables updates on agent machine - for Windows there is WM_SETTINGCHANGE event we could subscribe on to get updates, but it looks like there's no way to do this on Linux/OSX - please let me know if you have any insights

**Comment by simonsabin** [comment]
my view is that storing PATH as a capability is a hack and I agree that updating capabilities will be problematic if not controlled, thus the reason for the point 2. 

What we need is an extra method in say config.md that allows the capabilites to be updated. That way I can be in control of the process.

**Comment by anatolybolshakov** [comment]
@simonsabin you can also set up VSO_AGENT_IGNORE environment variables as 'PATH' - to ignore path variable during capability scanning.

**Comment by simonsabin** [comment]
Thats what I put in the docs change. https://github.com/MicrosoftDocs/azure-devops-docs/pull/10551 
The question is whether there is value in the agent including PATH as a capability, because it isn't and can't be used with any of the tagging to select agents with certain elements with in the PATH

**Comment by anatolybolshakov** [comment]
@simonsabin I'm closing this at the moment - please feel free to ask any further questions.

**Comment by simonsabin** [comment]
Given  #3228 removed psmodulepath, I see path as being exactly the same.
