### ISSUE TITLE
Guard against LFS compatibility issues when MinGit is 2.31.x or later.

### ISSUE THREAD

**Issue by mjroghelia** [microsoft/azure-pipelines-agent#3369]
We have broken customers when upgrading MinGit to 2.31.0 twice, first on the hosted pools with 2.184.1, then on a private MS pool in 2.185.0. The problem stems from the agent calling Git 2.31, which calls Git LFS, which then invokes an older version of Git from the PATH. See https://github.com/microsoft/azure-pipelines-agent/issues/3344

We need to guard against this in the future. When using the bundled MinGit can we have the agent prepend it to the PATH so LFS doesn't pick up an older git?

**Comment by DaniilShmelev** [comment]
> When using the bundled MinGit can we have the agent prepend it to the PATH so LFS doesn't pick up an older git?

Agent already prepends PATH with mingit, but this doesn't solve the issue since system `git-lfs.exe` also prepends it with system git path.
Possible solution: the agent could download `git-lfs.exe` as an external tool along with mingit, this way the agent won't have to reference system git in any way.
@mjroghelia waiting for your response on this matter.
