### ISSUE TITLE
[Question] How to make sure azure-devops self hosted agent run one build (not job) per time 

### ISSUE THREAD

**Issue by mo-saeed** [microsoft/azure-pipelines-agent#3391]
## Agent Version and Platform
Version of your agent? latest

OS of the machine running the agent? Linux

## Azure DevOps Type and Version
dev.azure.com

## What's not working?
I want to run only one build on the agent per time, I know the option of `--once` but this make it offline after first job in the build

**Comment by anatolybolshakov** [comment]
Hi @mo-saeed at one moment agent can run only one job per time - if you want some specific agents to run only one pipeline and not pick up jobs for others - you can use [demands](https://docs.microsoft.com/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml) to specify agents you want to execute it.

**Comment by mo-saeed** [comment]
Hi @anatolybolshakov so you can reproduce the same issue by running 4 builds in the exact same time and you have only 2 parallel jobs allowed.
you will see 2 jobs picked by the same agent in the same time.

**Comment by DenisRumyantsev** [comment]
Hi, @mo-saeed! We didn't manage to reproduce described behavior. Is this a spontaneous issue or you got it constantly? 

Could you please also share the following information so that we can continue our investigation:
- [Worker diagnostic logs](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#worker-diagnostic-logs)
- [Agent diagnostic logs](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#agent-diagnostic-logs)
- YAML file of your pipeline

Thanks!

**Comment by DenisRumyantsev** [comment]
Hi @mo-saeed, is this bug still actual to you?

**Comment by mo-saeed** [comment]
Hi @DenisRumyantsev, yes.. maybe we can have a call and I can share my screen to see that it's reproducible in my environment ?

I think it all happens when you start more than job exactly in same time (open 3 tabs in your browser with the same job) run 3 jobs in the same time. make sure all have the same agent pool.

maybe it happens with me coz I configure auto-provisioned agents, mainly when job arrives the queue a new agent is created in the agent-pool.. not sure
