### ISSUE TITLE
.env file and PATH variable

### ISSUE THREAD

**Issue by bdovaz** [microsoft/azure-pipelines-agent#3494]
In order to make the **Windows** self hosted agent configuration as portable as possible I have discovered the ".env" file that allows to add more environment variables but I have a doubt with the PATH variable.

Looking at the code I see that the only thing it does is to add the ones that are in that file but in the case of the PATH variable I see that it does not contemplate that special case because in that case what I would like is to take the PATH at the machine level and concatenate what has been added in the PATH variable in the .env file.

https://github.com/microsoft/azure-pipelines-agent/blob/b93f8f1f4e53ddf5d9cd25090db6f71b092d177c/src/Agent.Listener/Program.cs#L127

Is there any reason why this case has not been contemplated? Do you accept PR?

And one more doubt.

I see that in the special case of Linux agents there is a ".path" file that is created by itself (when configuring the agent) with the variables that it has at that moment in the PATH and later more can be added.

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops

Why does it work differently in each OS?

Are there more ".env" or ".path" like files that I don't know? I see that this part is not very well documented unfortunately.

**Comment by KonstantinTyukalov** [comment]
Hi @bdovaz, we are currently working on this issue and the described use case is not clear for us, so could you describe in more detail what you are currently working on making the agent more portable?

Based on the provided description, It seems you can create a script with the following content:

For PowerShell:
```pwsh
# override Path variable for the current terminal process
$env:Path += ";<YourAdditionalContent>"

# run the agent as usually do
.\run.cmd
```

For Bash:
```bash
# override Path variable for the current terminal process
export PATH=$PATH:<YourAdditionalContent>

# run the agent as usually do
.\run.sh
```

Could this solution fit your case? 

The process of getting environment variables works as follows:

Firstly, the agent adds/rewrites environment variables from the `.env` file for the process:
https://github.com/microsoft/azure-pipelines-agent/blob/b93f8f1f4e53ddf5d9cd25090db6f71b092d177c/src/Agent.Listener/Program.cs#L127

Secondly, the agent gets the environment variables of the process by using the build-in methods of `.Net platform`: https://github.com/microsoft/azure-pipelines-agent/blob/0eff66a89a2997626350ca78a2b884d6015574dc/src/Agent.Listener/CommandSettings.cs#L84

When the agent is configured to run as a service on Linux or macOS system, out of the box we have a `.path` file, which is used only in the following script:
https://github.com/microsoft/azure-pipelines-agent/blob/a3c8e472ad6927f4ea303e41b71f894ae95f34c1/src/Misc/layoutroot/env.sh#L40

We have no other configuration files for environment variables at the moment.

We will look at possible ways to unify the configuration of the agent and improve our documentation. We will give updates soon. Thanks for asking!

**Comment by bdovaz** [comment]
I'm not working on anything weird or specific, I just would like it to take as little time as possible to add new agents in the future or replace them (with newer hardware). That's why I'm talking about portability.

I would like the following functionalities to be cross platform and work in a homogeneous way:

- .env file: apart from the environment variables that it already resolves from the OS, to be able to add new variables. This is true in Windows and macOS but from what I read in the Linux documentation it is not? 

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops

"The snapshot of the environment variables is stored in .env file", does it mean that it does not resolve when starting the agent in real time the environment variables? I have not checked it (I only have agents currently on Windows and macOS) but the documentation makes me think that it works in a "static" way and works differently than a Windows agent that treats it additively.

- .path file: this file currently (or at least according to the documentation) only exists in a Linux agent. It would be very useful to have it in other OS to be able to make the agent configurations as portable as possible. And that it could work like the .env file in Windows, that is to say, in an additive way adding variables to the PATH variable.

**Comment by KonstantinTyukalov** [comment]
The main idea behind the `.env` file is to add new variables or replace the existing ones, and this file works equally on each OS. 

For the Linux/MacOs agent, we have a list of system environment variables that are fetched automatically, this list is predefined in the  `env.sh` script. The `env.sh` script itself just checks environment variables and writes them to the `.env` file, from where the agent reads values during the startup.

Here is a predefined list of environment variables:
https://github.com/microsoft/azure-pipelines-agent/blob/3a2d10a841e5af7c66cfa9fba7c8894cfc899f46/src/Misc/layoutroot/env.sh#L3-L18

Let me also briefly describe the order in which the agent gets information environment variables when it's configured to run as the service:

- Firstly agent reads PATH variable value from `.path` file, when it launches via `runsvc.sh` script: 

https://github.com/microsoft/azure-pipelines-agent/blob/3a2d10a841e5af7c66cfa9fba7c8894cfc899f46/src/Misc/layoutbin/runsvc.sh#L7-L11

- Secondly, the agent reads values from `.env` file (Note: If the `Path` variable was set here, it will override the value from `.path` file): 

https://github.com/microsoft/azure-pipelines-agent/blob/41a35136f3915fe7cb396d1b45a5882f2e663690/src/Agent.Listener/Program.cs#L116-L130

At the moment, we don't have plans to change the current agent configuration process, because the agent works in this way for a long time, and some customers depend on this behavior as well.

Also, answering your question about the PRs: Yes, we accept pull requests from the contributors so feel free to open a pull request and we will review it.

**Comment by KonstantinTyukalov** [comment]
@bdovaz, we have created a ticket on our internal board for an agent documentation update, so I just wanted to clarify if we are good to close this issue? Could you let us know if you have any further questions regarding the agent and environment variable?

**Comment by srinims** [comment]
ideally it should load all environment variable available to agent, rather than just set of list.  What is the gain of that.
