### ISSUE TITLE
We Stopped Hearing from Agents

### ISSUE THREAD

**Issue by jquintero88** [microsoft/azure-pipelines-agent#3499]
Who do we need to talk to about re-opening an ICM that we had about a year ago with this same issue? or is some one that can help resolve this issue? Thanks

**Comment by anatolybolshakov** [comment]
Hi @jquintero88 could you please elaborate more about your issue and fill in necessary info?

**Comment by jquintero88** [comment]
We are seeing self hosted agents get a we stopped hearing from agents error after 12+ hours. We have pipelines that run for up to 2+ days. Looking through diag logs seems like it is a problem with auth token expiring. we had this same issue last year and we thought it was mitigated only to start happening again. Don't know what exactly you need as far as necessary info. if you post any direct questions I can try to answer.

**Comment by jquintero88** [comment]
I spoke with @vijayma, 
@Rajesh Ramamurthy can you please help with token lifecycle and expiry.

**Comment by c002910** [comment]
We are having the similar issue with our pipelines, only on weekends (saturday & sunday). These pipelines will complete their builds within a hour, we are having autoscaling enabled for the agent pool as well. 

This issue is hapenning from July 31 2021.

**Comment by c002910** [comment]
@jquintero88 for us, this issue is happenning mostly on weekends, is it the same for your team as well?

**Comment by jquintero88** [comment]
@c002910  yes mostly on weekends, but we do see some during the week.

**Comment by DenisRumyantsev** [comment]
@jquintero88, I am closing this issue since it is most likely that this is a network issue and is not related to the agent itself. I will provide you with more info if it appears.

**Comment by c002910** [comment]
As per our analysis and testing with the MS support team, it seems to have worked fine when auto scaling was disabled.

This issue seems to got fixed with the Aug 19 release of Azure DevOps.

Ref: https://docs.microsoft.com/en-us/azure/devops/release-notes/2021/sprint-191-update

Below is the note related to the issue:
"Until now, these variables worked well with Windows scale set agents but not with Linux scale set agents because of an issue with the Azure Pipelines auto-scaling script. This issue has been addressed now. "
