### ISSUE TITLE
where can I find dotnet executable installed by this agent on a Linux VM?

### ISSUE THREAD

**Issue by siddjain** [microsoft/azure-pipelines-agent#3542]
This is a question rather than issue. Does the azagent install [dotnet](https://docs.microsoft.com/en-us/dotnet/core/install/linux-rhel) executable on a Linux VM? If so, where can I find it? Thanks.

**Comment by EzzhevNikita** [comment]
The agent is not installing Dotnet executable in the system, it is built in the way when all required runtime dependencies are included in the agent package. All required .net dlls are located in the bin folder inside the agent directory.

**Comment by siddjain** [comment]
So if we want the dotnet executable should we install it per the steps here (we are using RHEL):
https://docs.microsoft.com/en-us/dotnet/core/install/linux-rhel


  *   Do we have to follow all the steps?
  *   What version should we install to ensure there is no conflict with azagent? We are using 2.192.0 of azagent
  *   Do we have to install the SDK or the runtime to get dotnet executable?

Thanks
[https://docs.microsoft.com/dotnet/media/dotnet-logo.png]<https://docs.microsoft.com/en-us/dotnet/core/install/linux-rhel>
Install .NET on RHEL - .NET | Microsoft Docs<https://docs.microsoft.com/en-us/dotnet/core/install/linux-rhel>
The following versions of .NET are no longer supported. The downloads for these still remain published: 3.0; 2.2; 2.0; Remove preview versions. When using a package manager to manage your installation of .NET, you may run into a conflict if you've previously installed a preview release.
docs.microsoft.com


________________________________

**Comment by EzzhevNikita** [comment]
@siddjain If it is required to have a .net executable on your system, I think you can follow the instruction that you mentioned. Generally, you could install any required version of .net SDK, because the agent, in fact, is a self-contained package (it contains all required libs to run) and it is not using .net from the system, so it shouldn't conflict with .net Sdk installations in your system.
For example, if you will take a look at [virtual images](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md#net-core-sdk) that are used on systems where Microsoft hosted agents are running, you can see that there are different versions of .net SDKs on them and they do not conflict with an agent. Generally selecting of еру appropriate SDK version should be determined by the project and application you are going to build / run, not the version of the agent.

**Comment by siddjain** [comment]
Thanks @EzzhevNikita 

- Do we have to install the SDK or the runtime to get dotnet executable?

we need it for some other purposes

**Comment by EzzhevNikita** [comment]
@siddjain I believe it will be enough to have .net Runtime installation, but I don't your exact use case, so I couldn't say exactly. SDK is mostly required for development, while runtime contains just libs for running built applications. In fact, if you will install SDK, runtime also will be installed.

**Comment by EzzhevNikita** [comment]
@siddjain Could this item be closed?
