### ISSUE TITLE
Update to 2.193.0 gives error SP324097: Your network proxy requires authentication.

### ISSUE THREAD

**Issue by Rudi81** [microsoft/azure-pipelines-agent#3583]
Hello,

the agent automatically updated to version 2.193.0. Since then we can't release anything because we get the following error message:

SP324097: Your network proxy requires authentication.

We already had this problem after an update to version 2.188.3 so I told our customer to check their proxy settings. They told me that they are correct so I tryed to release again and it worked. They said they didn't change anything, so I don't know what has been the problem.

I hoped that the problem will be solved by itself again but this time like last time but this time it doesn't and we haven't released any code for two weeks now.

Customer told me that they maintained their server one week before the update so perhaps this could be the source of the problem but I am not sure about this.

**Comment by EzzhevNikita** [comment]
@Rudi81 Is it still an actual issue for you? I don't see any changes between those two agent versions that could affect proxy authorization, so my guess is that there were some changes in your environment like proxy settings that caused this issue.
Could you please share agent and worker logs if the issue is still actual?

**Comment by EzzhevNikita** [comment]
@Rudi81 Do you still experience this issue?
