### ISSUE TITLE
windows-2022 agent - Grunt@0 task not working

### ISSUE THREAD

**Issue by mariusandersen** [microsoft/azure-pipelines-agent#3645]
On windows-2019 we could just run with a pwsh task "yarn && grunt". 

In windows-2022 I previously had to use the dedicated [grunt task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/grunt?view=azure-devops) as it seemed grunt-cli was now removed. This worked for several weeks.

Today, the windows-2022 gives error using the Grunt@0 task:
##[error]Grunt-cli is not installed globally (or is not in the path of the user the agent is running as) and it is not in the local working folder: D:\a\1\s\node_modules\grunt-cli\bin\grunt

Can you fix the Grunt@0 task in windows-2022? 

Would also love it if you could globally install grunt-cli also, would simplify things for us.

**Comment by EzzhevNikita** [comment]
Hey @mariusandersen, Your issue is not exactly related to the repository of agent. As far as I see image windows-2022 really doesn't contain 'grunt-cli' package. Could you please submit an issue in the ['Virtual environments' repository](https://github.com/actions/virtual-environments), since the issue is related to their team?

**Comment by mariusandersen** [comment]
oh sorry yes will do
