### ISSUE TITLE
"Could not download kotlin-parcelize-compiler-1.4.32.jar" error in build pipe line job  on windows agent

### ISSUE THREAD

**Issue by disaini** [microsoft/azure-pipelines-agent#3687]
OS of the machine running the agent? Windows

If dev.azure.com, what is your organization name? 
https://onedrive.visualstudio.com/

## What's not working?

We are getting below error message very frequently  while run agent job

Logs :

* What went wrong:
Execution failed for task ':ListsControls:kaptGenerateStubsReleaseKotlin'.
> Could not resolve all files for configuration ':ListsControls:kotlinCompilerPluginClasspath'.
   > Could not download kotlin-parcelize-compiler-1.4.32.jar (org.jetbrains.kotlin:kotlin-parcelize-compiler:1.4.32)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-parcelize-compiler/1.4.32/kotlin-parcelize-compiler-1.4.32.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-parcelize-compiler/1.4.32/kotlin-parcelize-compiler-1.4.32.jar'.
            > Connection reset

Please help me  out, what could be the possible reason behind this and any fix for same ?

**Comment by alexander-smolyakov** [comment]
Hi @disaini, such an issue could be caused by the Azure SNAT balancer. If you are using Maven you can add: `-Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120` to your build command, it will force Maven to create new TCP connections from scratch every 2 min (with a 4 min threshold). For Gradle, you need to bump up the version up to `6.7.1` since from this version Gradle supports retries for connection resets.

**Comment by alexander-smolyakov** [comment]
@disaini is this issue still actual to you?

**Comment by disaini** [comment]
@alexander-smolyakov  you can close this, i have removed dependency  from maven.
