### ISSUE TITLE
Hosted Agent- Azure Container Instances -gtVersion 2.172.0

### ISSUE THREAD

**Issue by cheahengteong** [microsoft/azure-pipelines-agent#3694]
## Having issue with software on Hosted Agent?
I configure the hosted container instance agent and get an error 
"##[error]No agent found in pool aci-agent which satisfies the specified demands: Agent.Version -gtVersion 2.172.0"

Agent Platform:
Azure DevOps Services

**Comment by anatolybolshakov** [comment]
Hi @cheahengteong there seems to be demand in your pipeline - agent version should be greater than 2.172.0. 
You would probably need to update your agent, or at least make sure that auto-update is enabled for your agent pool.

**Comment by anatolybolshakov** [comment]
Hi @cheahengteong do you have any updates?

**Comment by cheahengteong** [comment]
@anatolybolshakov yes

**Comment by anatolybolshakov** [comment]
@cheahengteong is this issue still actual for you? Have the steps above helped you to resolve it?

**Comment by ceteongvanness** [comment]
You can refer to the https://medium.com/@cloudlabs01/running-azure-self-hosted-agent-in-azure-container-instance-aci-ad1fa338d769

**Comment by anatolybolshakov** [comment]
@ceteongvanness thanks! As I see there are instructions to set up self-hosted agent with azure container instance, although the error here seems to be related to demand required by some pipeline (agent version should be greater than 2.172.0). Seems like it was either configured with version less than 2.172.0, or there is some other possible reason).
@cheahengteong I'm closing this at the moment due to inactivity - please let us know if you have any questions.
For Azure DevOps related questions - you can also open a ticket on https://developercommunity.visualstudio.com/search?space=21 to get support
