### ISSUE TITLE
Windows 2.198.3 node10 folder referenced as /externals/node 

### ISSUE THREAD

**Issue by kirkpabk** [microsoft/azure-pipelines-agent#3742]
The externals/node10/ folder referenced by copy task as externals/node/ causing issue.

Upon installation, my quick workaround was to copy node10 into node until resolved.

Is there an oversight or something else that must be done?

It appears to be a hard-coded dependency and not compatible with node14, right?

**Comment by denis-tikhomirov** [comment]
Hello @kirkpabk,
I have checked behavior of CopyFiles task, but I couldn't repro the issue, task successfully copied dir node to node and node10 to node10 on windows-latest image.
Could you please share more details about occurred issue, details about repro environment, share pipeline yaml/details to repro the issue?

**Comment by denis-tikhomirov** [comment]
@kirkpabk, could you please share more details about occurred issue, details about repro environment, share pipeline yaml/details to repro the issue?

**Comment by kirkpabk** [comment]
So, when I install the 2.198.3 agent, there is no /externals/node directory, only a node10.   I've never seen a node10 directory in the...way back... 2.153.x version.   The only reason that I copied the node10 to node is because there was an error wherein the CopyFiles task indicated that it could not find "X:\AzureAgents\04\externals\node\bin\node.exe" as indicated in the output below.   There's really no additional details.   There just seems to be a disconnect.   I installed automated and manually multiple times with the same results.  No /node/ directory is ever created on my end, so I'm not sure what you're seeing on your repro environment @denis-tikhomirov.  As I state, I experimented and manually added the /node/ folder to get beyond the issue. Does this help, bro?

**TASK OUTPUT:** 
Starting: Copy Files 
==============================================================================
Task         : Copy files
Description  : Copy files from a source folder to a target folder using patterns matching file paths (not folder paths)
Version      : 2.164.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/copy-files
==============================================================================
##[error]This step requires a node version that does not exist in the agent filesystem. Path: X:\AzureAgents\04\externals\node\bin\node.exe
Finishing: Copy Files

**Comment by denis-tikhomirov** [comment]
@kirkpabk, thank you for providing info.
Looks like it's caused by issue during unpacking agent. I have checked package of agent 2.198.3 and it contains folders node and node10 both. All releases can be found here - https://github.com/microsoft/azure-pipelines-agent/releases.
I would suggest full reinstalling of agent (re-unpack agent package) as solution here.

But also it can be useful to find root cause of the occurred issue to have ability to prevent new repro in future.
Could you please share some additional info for us about the issue?
- how agent was unpacked/installed (new install with unpacking by command line like `[System.IO.Compression.ZipFile]::ExtractToDirectory` | new install with manual unpacking | automatic update)?
- do logs of used antimalware tool contain info about blocked items in agent folder?

**Comment by denis-tikhomirov** [comment]
@kirkpabk, do you have any updates here? Please let me know if full reinstalling of agent solved the issue.
Also would be great if you can share additional info about the occurred issue:
- how agent was unpacked/installed (new install with unpacking by command line like `[System.IO.Compression.ZipFile]::ExtractToDirectory` | new install with manual unpacking | automatic update)?
- do logs of used antimalware tool contain info about blocked items in agent folder?
