### ISSUE TITLE
Node version (6.17.1.0) flagged as vulnerability

### ISSUE THREAD

**Issue by craigeaw** [microsoft/azure-pipelines-agent#3812]
The latest version of the pipeline agent comes with Node v6.17.1.0 in the externals/node directory. This is getting flagged by our vulnerability reporting tool. Are there plans to update the node version to the latest version? Is there any harm in removing the externals/node folder?

**Comment by anatolybolshakov** [comment]
Hi @craigeaw there are plans to gradually migrate node version, but it could take some time since it depends on tasks migration https://github.com/microsoft/azure-pipelines-tasks/issues/15183
If you are not using tasks which are still not migrated to Node 10 - I believe it's fine to remove this node version from externals, probably the better option would be just use 'Alternate Agent Downloads' from [agent release page](https://github.com/microsoft/azure-pipelines-agent/releases) which don't have node 6.

**Comment by craigeaw** [comment]
@anatolybolshakov this is good info, thank you! I didn't see the alternate agent downloads before. I think that should satisfy our needs for now.
