### ISSUE TITLE
VSTS Agents Self Hosted on a Mac

### ISSUE THREAD

**Issue by dmccolloughOneGas** [microsoft/azure-pipelines-agent#3832]
Question, I would like to run my self hosted Mac build agents as a daemon on my Mac mini so that I don't have to login to the Mac using the service account.

I have them running as launchd services, they work perfectly if I login to the Mac mini using our service account. This presents a problem if the server reboots for something, we are mostly working from home, so if it reboots and the build agents don't start. Somebody has to drive into the office and login and get them running.

Yes I know we can configure the mini to automatically login, however our security team would prefer to not do this.

I've also reviewed the following documentation, we do not want to automatically login and lock.
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-osx?view=azure-devops#automatic-login-and-lock

So is it possible to get the build agent running as a launchd service to run as a daemon ?
If so, any specific documentation that somebody could provide would be greatly appreciated.

**Comment by neoswallow** [comment]
I haven't actually tried it myself but https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-osx?view=azure-devops#alternative-service-mechanisms has an Apple site link (https://developer.apple.com/library/content/documentation/macOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html) to setup Launch Deamon/Agent.

In my case, I setup port forwarding of ssh along with screen share to the mini so that I don't have to run to the office unless it's shutdown and does not start back up.

**Comment by dmccolloughOneGas** [comment]
@neoswallow I appreciate the response, I gave the apple document a try and couldn't get it to work. Hoping that Microsoft will review and respond.

Thanks

**Comment by anatolybolshakov** [comment]
Hi @dmccolloughOneGas as I know there is no other supported ways to run it - have you checked the links below as well (mentioned in docs)?
https://www.engadget.com/2011/03/07/terminally-geeky-use-automatic-login-more-securely/
https://lifehacker.com/5779922/make-os-x-load-your-desktop-before-you-log-in

I would suggest to reach out to the Apple support for the best practices for your case.
