### ISSUE TITLE
ADO Agent Going Offline Intermittently

### ISSUE THREAD

**Issue by colta95** [microsoft/azure-pipelines-agent#3911]
I have a bunch of self-hosted ADO agents running on windows 11 machines. They're running in a command prompt (not as a service) because we sometimes want to turn off the agent while we test something on the machine.

Occasionally, an agent would show up as offline on the "Agent pool" page, even though the machine is still running and after I've set the machines to high performance mode - so they shouldn't be sleeping. I would then have to remote desktop into the machine and press enter in the command prompt, which causes it to go online again. 

It then prints out that an error has occurred, and from the log file it looks like a 401 authentication failure. Here's one of the log files:
[Agent_20220718-153447-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/9142181/Agent_20220718-153447-utc.log)

Is there some way to fix this issue? We're running daily pipeline jobs on these machines, and these will fail whenever one of the agents are offline.

Also, is there a way for an ADO pipeline job to skip an agent if it's offline? Sometimes we may be actively working on a machine and we would like to skip it if a pipeline job runs.

Thanks!

Agent version: 2.202.1
OS: Win 11

**Comment by KonstantinTyukalov** [comment]
Hi @colta95, thank you for reporting. At this moment we are working on higher priority tickets, but will get back to this one soon.

>Also, is there a way for an ADO pipeline job to skip an agent if it's offline? Sometimes we may be actively working on a machine and we would like to skip it if a pipeline job runs.

Are you referring to replacing an agent for a job already in progress? This is not possible because the agent stores the context of the running job locally.
You can skip the desired agent when executing a pipeline only if the job has not yet been started.
For pipeline execution, Azure DevOps will select agents which are online and meet the demands. If in your case ADO selects offline agents before the job execution, please tell us.

Thank you

**Comment by colta95** [comment]
Hey @KonstantinTyukalov! Thanks for the reply!

In our case, we're running the pipeline on every machine in the test lab for each run, because each machine has different hardware configurations.

We specify the agents to run in the yml script with this line:  `demands: Agent.name -equals $(agentName)`. And under the `strategy` field we have a `matrix` that lists each machine and their `agentName`.

And if one of our agents are offline, the pipeline will still try to run the job on the agent, which causes it to stall.
