### ISSUE TITLE
Support for using `--no-tags` instead of always `--tags`

### ISSUE THREAD

**Issue by scottdallamura** [microsoft/azure-pipelines-agent#3913]
Currently checkout steps always use `--tags`.  Azure DevOps is adding support to the UX and yaml to control this behavior, in order to help customers more easily have quicker checkouts.

For old designer builds, the server will augment the repository properties with a `fetchTags` property with a value of `false` if the user opts-out of fetching tags
For yaml pipelines, the checkout task will support a `fetchTags` property

Before the UX can turn these experiences on, the agent needs to be able to support them.

**Comment by alexander-smolyakov** [comment]
@scottdallamura thanks for your contribution! 

The related PR was completed:
- #3907

We will update this issue as soon as the related changes are rolled out to all ADO customers.

**Comment by mkot02** [comment]
I tested `featchTags: false` option (agent version 2.213.2) and it looks like it's still not working properly when the repository in unshallow copy (fetchDepth: 0). The problem is that agent it always running with --prune-tags option which causes git to actually fetch tags. This is documented in **PRUNING** section of (git-fetch)[https://git-scm.com/docs/git-fetch#_pruning] documentation:

> The --prune-tags option is equivalent to having refs/tags/*:refs/tags/* declared in the refspecs of the remote. This can lead to some seemingly strange interactions:
> ```
> # These both fetch tags
> $ git fetch --no-tags origin 'refs/tags/*:refs/tags/*'
> $ git fetch --no-tags --prune-tags origin
> ```

Should I create a new issue or comment here would be sufficient as this issue is not closed yet?
