### ISSUE TITLE
Azure Devops pipelines failing since Current agent version changed from '2.204.0' to '2.206.1'.

### ISSUE THREAD

**Issue by GeorgeFoxRazor** [microsoft/azure-pipelines-agent#3914]
I have an Azure devops pipeline that is running on ubuntu-latest. It uses a Docker image to run DBT commands. It uses a Hosted Agent and was working fine until the Current agent version changed from '2.204.0' to '2.206.1'. Since the updgrade it has been throwing the error ##[error]Bash exited with code '139'. The step that is throwing the error is docker run docker-image:latest dbt source freshness.

There is another pipeline which has also stopped working since the upgrade of the Current agent version from '2.204.0' to '2.206.1'. This pipeline uses the AzureCLI@2 task to trigger an ADF pipeline. It is now throwing the error '##[error]Script failed with exit code: 1' 

There have been no changes on either pipeline between it working (8th of July) and not working (18th of July).

**Comment by DenisRumyantsev** [comment]
Hi @GeorgeFoxRazor, could you provide pipeline debug logs, agent diagnostic logs, and worker diagnostic logs for successful and failed runs to compare? To get these logs, could you run both pipelines with `System.Debug` and `agent.diagnostic` pipeline variables enabled (set to `true`)?
```yml
variables:
  System.Debug: true
  agent.diagnostic: true
```
Could you also provide the Docker image and repro-steps to help us to reproduce this issue?

To prevent security issues, you can send these logs to these emails:
* v-denisr@microsoft.com
* akvelon-build-tasks@microsoft.com


["Review logs" documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs)

**Comment by DenisRumyantsev** [comment]
@GeorgeFoxRazor, I have got logs, thanks.
As far as I can tell, the agent itself is doing its job well, and versions of tasks used in the pipeline are the same.
But the agent uses a different environment in the working case ([20220626.1](https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220626.1)) and in the case with the error ([20220717.1](https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220717.1)).
I wonder if this issue could be caused by changes in the environment.

So, could you try this and check in which case your pipeline failed or succeeded:
* create a new self-hosted agent pool (`project settings` -> `agent pools` -> `add pool` -> `new` -> `self-hosted`);
* configure and run two self-hosted Linux agents in it, versions [2.204.0](https://vstsagentpackage.azureedge.net/agent/2.204.0/vsts-agent-linux-x64-2.204.0.tar.gz) and [2.206.1](https://vstsagentpackage.azureedge.net/agent/2.206.1/vsts-agent-linux-x64-2.206.1.tar.gz);
  you can run these commands from the agent folder root:
  * configure: `sudo ./bin/Agent.Listener configure --unattended --url "https://dev.azure.com/<organization>" --pool "<self-hosted-agent-pool-name>" --agent "<linux-agent-name>" --auth "PAT" --token "<token>" --acceptTeeEula`
  * run: `sudo ./bin/Agent.Listener`
* run your pipeline using different agents in this pool;
  you can disable another agent in the pool settings, or just shut it down (`ctrl` + `C`)

**Comment by GeorgeFoxRazor** [comment]
Thank you for getting back to me @DenisRumyantsev ,

I have run the pipeline on the two self hosted agent versions (2.204.0 and 2.206.1) but I am getting the same bash 139 error as before on both of these agents as well as on the hosted agent. I don't think the issue can be with the environment as when I run the docker container locally and run the same commands it works fine without errors.

**Comment by max-zaytsev** [comment]
Hi @GeorgeFoxRazor, is this still actual for you?

**Comment by kirill-ivlev** [comment]
@GeorgeFoxRazor we didn't receive your response, I will close this item as inactive, please re-open it if the issue is still actual for you.
