### ISSUE TITLE
TF issues and enhancements

### ISSUE THREAD

**Issue by ericsciple** [Microsoft/azure-pipelines-agent#398]
- [ ] Computer name truncation issue wrt TEE. [Details](https://github.com/Microsoft/vsts-agent/issues/203)
  - MAX_COMPUTER_NAME_SIZE = 31; Either match TEE logic or omit computer name comparison.
- [x] Computer rename resiliency when local cache does not exist (hosted agent scenario). PR https://github.com/Microsoft/vsts-agent/pull/396
- [ ] Computer rename resiliency when local cache does exist. Need to investigate more.
- [x] Add TF and TEE to the PATH
- [ ] Pass login creds via env var and leave in environment if "Allow Scipts Access to OAuth Token" is checked (TF.exe and TEE).
- [ ] Always provide Build.SourceTfvcShelveset. [Details](https://github.com/Microsoft/vsts-agent/issues/46)
- [ ] Support scorch for tf.exe when the workspace doesn't have a root mapping (e.g. `c:\a\1\s` is not mapped). Current behavior warns, throws away workspace, and creates a new workspace.

**Comment by ppejovic** [comment]
@ericsciple 

> Support scorch for tf.exe when the workspace doesn't have a root mapping (e.g. c:\a\1\s is not mapped).

`tf vc scorch` will allow a wildcard in the `itemspec` so you can pass `c:\a\1\s\*` to the command. I have tested this with a workspace without a root mapping.

This issue is causing us significant problems for builds that have many mappings (100+) without a root mapping. The **Get Sources** step time increases by 300-400% when upgrading from the v1.105.6 agent to the v2.112.0 agent because `tf vc workfold /map` is run for every mapping on every build.

It seems a simple fix [here](https://github.com/Microsoft/vsts-agent/blob/1a5db85766912fdccf6983e8af76a6b5f4584cf9/src/Agent.Worker/Build/TFCommandManager.cs#L80) unless I'm missing something?

`public async Task ScorchAsync() => await RunCommandAsync(FormatFlags.OmitCollectionUrl, "vc", "scorch", $"{SourcesDirectory}\*", "/recursive", "/diff", "/unmapped"); `

i.e. something like changing the argument `SourcesDirectory` to `$"{SourcesDirectory}\*"`

**Comment by ericsciple** [comment]
lets discuss on a separate issue, i dont want to clutter this issue with discussion since this issue is intended as an enhancements checklist.
