### ISSUE TITLE
Secure Variables are Showing in output

### ISSUE THREAD

**Issue by pgunerud** [microsoft/azure-pipelines-agent#4008]
## Agent Version and Platform
Version of your agent? 2.211.1 x64

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
Azure DevOps Server 2020 Update 1.1

If on-premises, which release? 2015.0, 2017.1, 2019 RC2, etc.
2020 Update 1.1

## What's not working?
I ran a pipeline that contains secure variables and set system.debug=true when looking at the inputs of a task the secure variable value shows as plain text.

![image](https://user-images.githubusercontent.com/51721966/198073339-20b48413-3bac-410d-bfea-b52b5735efbd.png)

**Comment by DmitriiBobreshev** [comment]
Hi @pgunerud thank's for the report! An agent using [SecretMasker](https://learn.microsoft.com/en-us/dotnet/api/microsoft.teamfoundation.distributedtask.expressions.evaluationcontext.secretmasker?view=azure-devops-dotnet) from ms, you can see [code here](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Sdk/Util/LoggedSecretMasker.cs), I tried to reproduce your error (as I can see on the screenshot you're using CmdLine Task), but wasn't be able to reproduce the bug.

![image](https://user-images.githubusercontent.com/106314398/198617419-21948845-6219-4240-8244-b9c5e0ef37b8.png)


Could you please provide some additional info? Such as:
- short pipeline example if it's possible
- secret variable name pattern(maybe this happen because of an uncommon name)
- also if you're using docker in the pipeline (you said that the error is on the windows machine but I see Linux output on the screenshot), please provide some info about it

 Thanks.

**Comment by DmitriiBobreshev** [comment]
Hi @pgunerud  do you have any updates?

**Comment by DmitriiBobreshev** [comment]
Hi @pgunerud, I'm closing the task due to inactive, please feel free to reopen it in any case of the problem.
