### ISSUE TITLE
[enhancement]: Add new agent capability that allows repositories to be checked out below work directory level on self hosted agents

### ISSUE THREAD

**Issue by echalone** [microsoft/azure-pipelines-agent#4192]
### Describe your feature request here

This is a feature request for a new agent capability that would allow self hosted agents to check out repositories below the work directory level (so for example below "/_work", instead of just below the build pipeline directory level for example "/_work/1"), so large repositories can be shared between build pipelines without taking up space for each and every pipeline.
This feature should be disabled by default as pipelines could otherwise interfere with each other on public agents or users on public agents could change configuration files below the work directory, which would pose a security risk.
It could for example be activated by passing a flag to the configuration command in the command line when configuring the agent.

**I would have already implemented this feature as described and have already created a pull request** to the master branch of this repository: https://github.com/microsoft/azure-pipelines-agent/pull/3475
**The pull request needs to be reviewed and accepted.**

A more thorough description of how the feature was implemented can be found in the pull request.

PS: I'm reopening/readding this issue since https://github.com/microsoft/azure-pipelines-agent/issues/3951 (and previously https://github.com/microsoft/azure-pipelines-agent/issues/3483 ) were wrongfully closed by a stale-bot, it's not really stale, it just hasn't been processed yet

**Comment by OranguTech** [comment]
A couple notes:


1 - There's few things more maddening to me in the tech world than asking a question and someone without the context telling you "you're doing it wrong", but I'm going to risk doing that same thing. Have you considered other approaches to dealing w/ large repos? Shallow clones, only checking out a specific branch, etc?

If you're not familiar or in case it helps someone else:
https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/

2 - Your feature request specifies a particular approach to the problem, perhaps it should be more like "...that allows repositories to be checked out to a shared directory" or possibly even more generically rather than assuming /work/. My understanding of how the build process works is that there are a lot of assumptions built into how the agents do their work, directory structure, etc, and what you're trying to do probably violates those assumptions, and may require more changes than you think.

**Comment by echalone** [comment]
> A couple notes:
> 
> 1 - There's few things more maddening to me in the tech world than asking a question and someone without the context telling you "you're doing it wrong", but I'm going to risk doing that same thing. Have you considered other approaches to dealing w/ large repos? Shallow clones, only checking out a specific branch, etc?
> 
> If you're not familiar or in case it helps someone else: https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/
> 
> 2 - Your feature request specifies a particular approach to the problem, perhaps it should be more like "...that allows repositories to be checked out to a shared directory" or possibly even more generically rather than assuming /work/. My understanding of how the build process works is that there are a lot of assumptions built into how the agents do their work, directory structure, etc, and what you're trying to do probably violates those assumptions, and may require more changes than you think.
> 
> Edit: I wonder if adding agent support for WorkTrees would help?

Thank you for your considerations but not only am I familiar with the agent I also already did the needed changes, tested them successfully and the pull request is active. I've considered all scenarios and assumptions of how the agent works and how it uses directories ;)
Please see the linked Pull Request for more details. You can test those changes too if you like.
