### ISSUE TITLE
[BUG]: Consider changing After=network-online.target instead of After=network.target

### ISSUE THREAD

**Issue by benlongo** [microsoft/azure-pipelines-agent#4319]
### What happened?

Just noticed this while modifying the unit file, but I believe it should be `After=network-online.target` instead of `After=network.target` ( see <https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/>). Could be wrong about this though. 

### Versions

Pipelines agent v3.220.5 / Linux

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

**Comment by DmitriiBobreshev** [comment]
Hi @benlongo, thanks for the reporting! We will check and come back with the results

**Comment by pixdrift** [comment]
Reading the doc provided @benlongo I think this is an interesting comment about `network-online.target`

_It is strongly recommended not to pull in this target too liberally: for example network server software should generally not pull this in (since server software generally is happy to accept local connections even before any routable network interface is up), its primary purpose is network client software that cannot operate without network._


I also looked at the default unit file for Apache (httpd) in RHEL 8 as an example to compare and it uses `network.target`

```
[Unit]
Description=The Apache HTTP Server
After=network.target remote-fs.target nss-lookup.target
Documentation=man:httpd(8)
Documentation=man:apachectl(8)
```

Not sure what distro you're using, but would be interested to know what other services use in that distro?

Have you had any issues with timeouts or agent communication with `network.target`?
