### ISSUE TITLE
[Question]: Will there be a stable/final 2.200.x version of the agent?

### ISSUE THREAD

**Issue by TMattes** [microsoft/azure-pipelines-agent#4322]
### Describe your question

Will there be a stable/final 2.200.x version of the agent?

### Versions

Azure DevOps Server Version 2022.0.1
Agent version 2.200.x (now working with agent version 2.217.2)

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Azure DevOps Server Version (if applicable)

Azure DevOps Server 2022.0.1 (AzureDevOpsServer_20230418.1)

**Comment by vmapetr** [comment]
Hi @TMattes, thank you for your question!

To support the newer hardware and operating systems we had to use the .NET 6 version, which was implemented in the agents 3.*, besides that the 2.* agents use the .NET Core version 3.1 which support ended on December 13th, 2022. For the first quarter of 2023, we have updated our hosted pools with the new agents and gathered feedback for them. However, now the migration is complete and we are not planning further 2.* releases.

However, since many customers still rely on the 2.* version, we'll provide the necessary updates for it in case security vulnerabilities will be discovered.

Please, notice that you can still use agent 2.* but if you plan to keep up with the Azure DevOps Server releases in the future or use the Azure DevOps Service, it is recommended to update your agents to version 3.*, since further updates of the Pipelines may require a new agent version.

**Comment by vmapetr** [comment]
Hi @TMattes,
I'm closing this ticket, please feel free to reopen it in case you have additional questions.
