### ISSUE TITLE
[Question]: Self hosted agent fills up server storage

### ISSUE THREAD

**Issue by edgariscoding** [microsoft/azure-pipelines-agent#4340]
### Describe your question

We have two azure self hosted agents running on a single server.

Everything works fine for a few days then suddenly we get the following error during builds: `ENOSPC: no space left on device`

The _work directories for each agent have grown to a size that completely filled up the server's storage.

We have the build pipeline configured to clean up before starting a build. And we have a maintenance schedule set up for the agent pool.

The only instant solution is to SSH into the server and `rm -rf` the two `_work` agent directories. 

Is there any way to automate this? What are we doing wrong?

### Versions

Azure agent 2.213.2

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 20.04

### Version controll system

git

**Comment by DenisRumyantsev** [comment]
Hi @edgariscoding, so, you are using self-hosted Ubuntu 20.04 agent version `2.213.2`. Is it right that each time you run your pipeline, the agent creates a new `_work/X` folder (where `X` is some number)? If so, could you share a pipeline yml file example to reproduce this issue?

**Comment by edgariscoding** [comment]
@DenisRumyantsev im using classic pipelines so i don’t have a yaml file

**Comment by DenisRumyantsev** [comment]
@edgariscoding I was not able to reproduce this issue.
Could you check if your self-hosted agent creates a new `_work/X` directory each time you run the same pipeline?

**Comment by pixdrift** [comment]
I am also seeing this issue on our ADO pipeline container servers (high disk usage, and cleanup not appearing to work correctly).

It has been difficult to pinpoint exactly what is triggering the behaviour in each repo as it's not always the work directory. One theory was it was due to failed/testing pipelines or ageing artefacts. We regularly see high usage in `/var/tmp` which I believe is artefact related and temporary, and also under `_work/s/.git` with large numbers of packfiles, even when we attempt to limit the `fetchDepth` configuration in the pipeline.

I am interested to know if the `.git` directories are unreasonably large (ie. much larger than the expectations based on repo size) in your experience too @edgariscoding?

The part that was surprising to me moving to self hosted agents was the persistence of the working directory across pipeline runs by default which is different default behaviour to the Microsoft hosted cloud/container agents as they are truly ephemeral and destroyed. This was an unexpected behaviour to me coming from other tools, as one of the major benefits of using containers for builds is that they are ephemeral and build environment is clean/consistent, but in ADO the volume is mounted in from the host and re-used. This workspace behaviour is also inconsistent for the end user as the job may be executed on a different ADO agent/runner, so it has limited utility and I do question its configuration as the default behaviour.

The only way I have found to ease (not resolve) the workspace filling up due to the default persistence configuration is to ensure pipelines are configured to clean up the workspace in the yaml pipeline configuration (I believe classic also has an option to clean workspace but I don't use classic). You mentioned you were doing this @edgariscoding, are you using the same configuration that I am using for self hosted pipelines?:

```
- job: MyJob
  workspace:
    clean: all
```

The documentation on workspace cleanup doesn't make all of this very clear..
https://learn.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#workspace

Noting the following comment from the above page:
**_The workspace clean options are applicable only for self-hosted agents. Jobs are always run on a new agent with Microsoft-hosted agents._**

As a side note, I really believe that workspace cleaning configuration should be an ADO agent option, as currently we depend on the owners of pipelines to specify this configuration, and if they don't specify the configuration they get inconsistent behaviour between cloud hosted and private hosted agents.

**Comment by yitasha** [comment]
![Image](https://github.com/user-attachments/assets/07390d4d-c6bb-4d6f-bbf5-d6fe095bbc8f)

This problem still exist in the self hosted agent on Amazon Linux EC2,
it's not getting cleaned up after each run, and it's building up the storage now.

I can confirm it will create new **_work/X** for running same/different pipeline, it doesn't create one per run, but it will eventually create one.

**Comment by shatodj** [comment]
The problem still exists. We need to clean the disk manually for now, as we are looking for a retention strategy for the future. 
```
workspace:
    clean: all
```

...and this is not working very well.
