### ISSUE TITLE
[Question]: Poor task restore perfomance

### ISSUE THREAD

**Issue by strat-alex** [microsoft/azure-pipelines-agent#4457]
### Describe your question

Hi,

I'm having several performance related issues with self-hosted Windows 2022 build servers.
I am running a VMSS setup with latest (last weeks latest) runner images as listed here: https://github.com/actions/runner-images .

The first issue I found was that npm restore performance was quite bad. I tried adding a cache step to that build but the results were unstable. Compared to the MS hosted server, there was a noticeable difference (bottom = MS hosted, top = self hosted on VMSS without cache step).
![image](https://github.com/microsoft/azure-pipelines-agent/assets/29447652/e725a9e4-498c-4109-a551-48887169a629)

With npm cache step it's ranging from 11-17minutes. So not really a stable improvement.

Ok. So, there's an issue.
Doing a network performance test with the ubuntu image vs the windows 2022 images, shows something is up.
The ubuntu download speed from Ookla was 15Mbps,
The windows download speed from ookla was 5Mbps.

Ok, so maybe it has something to do with the network.
Checked the RSS (Receive Side Scaling) settings, but they're fine according to me (enabled, default cpu 0).

Next step in my thinking: ok, without going into the depths of performance recorder on a bloated build VM. Let's just setup a clean VM in our network, and register a latest ado agent. But no noticeable improvements.
The people over at the runner-images repository advised to disable the storsvc service, to improve performance. But that resulted in no improvement for me.

During testing I found that some of the devops agent restore tasks are also slow.
The PublishBuildArtifacts task is fast:
![image](https://github.com/microsoft/azure-pipelines-agent/assets/29447652/28ecffbf-d634-4507-9e05-f70aac7deb72)

But the AzurePowershell task is slow:
![image](https://github.com/microsoft/azure-pipelines-agent/assets/29447652/cff3fac4-8d25-49c8-b6e9-0c1e805c5b65)

We are currently running behind an azure firewall, so I also tested this running in an Azure VM that is not connected to our network.

The size of the VM's I'm running with are either: D4as_V4 or D4s_v4.

I wanted to try a preview agent, but whenever a pipeline starts, it is downgraded to the current version.

Currently I don't really know what my next steps should be to troubleshoot this issue. Could someone advise?

### Versions

Azure Devops agent version 3.225.0
Windows Server 2022

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [X] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows Server 2022

### Version controll system

git

**Comment by ivanduplenskikh** [comment]
Hi @alexv-be thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by alexv-be** [comment]
Some updates:
Last week I’ve done quite a bit of network performance testing on the VM’s in West Europe.
Our setup has a VWAN + Azure Firewall in there. However: the VNET connected to the VWAN does not have firewall protection enabled (yet) + the firewall does not do IDS or TLS inspection. So any real delays should not come from that area.
To be clear, I am/was using D(a)s_v4 VM’s to test. I'm not using VMSS' to test, I know they could be different in terms of behavior, but so far they seem to behave very similar.

![image](https://github.com/microsoft/azure-pipelines-agent/assets/29447652/3da459c4-4cfd-499d-88d1-2bc188662169)

These VM’s have a somewhat 'limited' bandwidth scope:
![image](https://github.com/microsoft/azure-pipelines-agent/assets/29447652/005f66b8-ffc5-4c1c-85dc-0523e4181206)

Or for the Das_v4 family:
![image](https://github.com/microsoft/azure-pipelines-agent/assets/29447652/dd1e3b1a-30a9-4c54-9103-0300a6231ca5)

4Gbps = around 500MBps which should still be more than enough for getting npm packages or getting azure devops tasks.
Now, the performance, tested using ookla speedtest looks like this:

![image](https://github.com/microsoft/azure-pipelines-agent/assets/29447652/7c111213-62ba-44c5-887f-19f3c3dc6e23)

The first RDP session on the left: is a blank windows 2022 datacenter VM in a VNET connected to the VWAN (unsecured).
The second RDP session on the left: is the windows 2022 VM based on the Windows Runner image from the github repo, also connected to the same VNET.
The SSH session (third from left): is a base Ubuntu 2022 VM also connected to the same VNET.
The fourth RDP session is a blank windows 2022 VM, running in a standalone VNET not connected to the VWAN.
I did another test with a linux vm outside of our VWAN’d network, and those download speeds were over 15000Mbps easily. I don’t have a screenshot anymore. But I can say that linux download performance was noticeably better in all scenario’s.

Side note: I tested this with the speedtest command lines tools on windows too, and the download speeds were consistently better, but not by much.
What is really nice to see is that the Linux VM almost consistently delivers more than the specs. Although this 13000Mbps download speed was not consistent, it went to 8000Mbps in some tests. But during my tests, at least 70% was over 10000Mbps. Admittedly on a rather small sampling set.
The windows VM’s never got over 9000Mbps. Which, in my opinion, is still reasonably within the spec.
 
The differences are noticeable. And honestly, I was a bit surprised. But, even on the slowest test, 5600Mbps is still easily going strong at 700MBps. Again, in my opinion, more than enough bandwidth for download streams like npm or azure devops tasks. Would I like to see this higher consistently? Yes. If you have pointers, I’m all ears.
 
 
But, you know, just in case my assumption is wrong, let me test with a v5 series VM (according to the docs 12.5Gbps network bandwidth)
![image](https://github.com/microsoft/azure-pipelines-agent/assets/29447652/412ca81f-b050-4a63-b3cf-1621a8c344a2)

So this was worse, kind of. Maybe worth looking into it why it’s like that. Maybe a non-AMD series would be better? But it wasn’t (no screenshot anymore). I stopped testing the v5’s, because I didn’t really see the point in repeating those tests with the same tools.


I decided to take some time and do a performance analyzer session on the clean windows VM. And there was a noticeable issue when extracting the downloaded azure devops tasks. It took over 20seconds to extract the "Downloading task: DownloadBuildArtifacts (0.225.0)" and another 20+ to extract: "AzurePowerShell (5.228.0)".
MsMpEng.exe and other defender related items popped up.
So I made sure these were added: https://learn.microsoft.com/en-us/troubleshoot/azure/devops/antivirus-scanning-exclusions . And I also tried disabling defender for the VM entirely.

I can see improvements, but it's not to the point where it should be yet.
![image](https://github.com/microsoft/azure-pipelines-agent/assets/29447652/d4e1eef7-a78e-4934-95b3-80500136c0e7)


![image](https://github.com/microsoft/azure-pipelines-agent/assets/29447652/818754f3-bbd9-4e0e-966e-558130d66897)

The results are not consistently *that* good, but it hasn't gone above 35s checkout time anymore.

I have some other projects right now, but when I get back to this:
- I'll do a performance recording again of the current state. 
- Someone advised using a different azure region. I'm limited to European ones, but I can try that for sure.
- Anything else this forum advises.

**Comment by vmapetr** [comment]
Hi @strat-alex could you please confirm if issue still occurs?

**Comment by vmapetr** [comment]
Hi @strat-alex could you please let us know if the issue is still relevant?

**Comment by strat-alex** [comment]
Hi, sorry for the late reply. I'm checking with the team that reported it. They're hard to reach due to holidays left and right. I'll get back to you as soon as I have news.
