### ISSUE TITLE
[Question]: Self Hosted Agent : Git Fetch : fatal: not enough memory for initialization

### ISSUE THREAD

**Issue by mailtocprakash** [microsoft/azure-pipelines-agent#4570]
### Describe your question

Checkout Task Fails in Self Hosted Agent
during git fetch throws below error
"fatal: not enough memory for initialization"

pls help here

### Versions

vsts-agent-win-x64-3.230.2

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

**Comment by DmitriiBobreshev** [comment]
Hi @mailtocprakash, please check that you have enough free memory on the machine where the agent is running. 
If you use large repositories you could try [shallow fetch](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops&tabs=yaml#shallow-fetch). 
In some cases might help to enable option [FIX_POSSIBLE_GIT_OUT_OF_MEMORY_PROBLEM ](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Sdk/Knob/AgentKnobs.cs#L127) variable, if the option is enabled, mingit [2.42.0.2](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Misc/externals.sh#L22) will be used instead of the 2.39.1.

**Comment by mailtocprakash** [comment]
I have unzipped the agent in C: drive in Azure VM, where it has 114 GB free space is available and my git repo size is 20 MB only.

Can you elaborate how to set the [FIX_POSSIBLE_GIT_OUT_OF_MEMORY_PROBLEM ] variable in sel-hosted agent VM machine? or in pipeline ?

**Comment by DmitriiBobreshev** [comment]
@mailtocprakash, the error itself says that you don't have enough free RAM memory. You can set [FIX_POSSIBLE_GIT_OUT_OF_MEMORY_PROBLEM ](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Sdk/Knob/AgentKnobs.cs#L127) as a [Pipeline variable](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#understand-variable-syntax) or as os env variable

**Comment by mailtocprakash** [comment]
Increased the size of the VM from 1 GB RAM to 4 GB RAM, Now Git fetch started working.

Thanks a lot @DmitriiBobreshev
