### ISSUE TITLE
[Question]:  Microsoft.Azure.DevOps.Pipelines.Agent VM extension releases

### ISSUE THREAD

**Issue by rybal06** [microsoft/azure-pipelines-agent#5040]
### Describe your question

It looks like this VM extension in Azure (required when using VMSS agents) is out-of-date. This is added automatically by Azure DevOps when using VMSS agent pools.

In the settings block; we see the agent version as 3.236.0 (released February 2024)

```json
{
  "isPipelinesAgent": true,
  "agentFolder": "/agent",
  "agentDownloadUrl": "https://vstsagentpackage.azureedge.net/agent/3.236.0/vsts-agent-linux-x64-3.236.0.tar.gz",
  "enableScriptDownloadUrl": "https://vstsagenttools.blob.core.windows.net/tools/ElasticPools/Linux/16/enableagent.sh"
}
```

We are using VMSS with ephemeral agents, so it is not practical to install a previous version of the agent and then wait for it to update each time the VMSS instance is replaced by Azure DevOps reimage operations.

Questions:

1. When and how is the Microsoft.Azure.DevOps.Pipelines.Agent VM extension updated to reference the latest GA version of the agent package?

2. How can we become aware of when the VM extension is updated to use a newer agent version?

3. Is there any particular reason that the extension is still referencing 3.236.0 (awaiting QA, bug found,etc)?

### Versions

VM extension version: 1.26
Agent version: 3.236.0
Ubuntu 20.04 LTS

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [x] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 20.04LTS

**Comment by elessard-genetec** [comment]
I've observed the same behavior, and in my case this caused our pipelines to start failing since we are depending on a feature that was added in the Agent version 3.240.1.

Looks like Azure DevOps service updated the VMSS extension of our VMSS in the past 24 hours, and the new VMSS extension is actually configured to download an _older_ version of the Agent (previously, Agent version 3.246.0 was downloaded, at least for the past couple of weeks).

**Comment by elessard-genetec** [comment]
> I wonder if the service team found an issue in 3.246.0 and reverted all customers to 3.236.0?

I'm a bit surprised to hear that, from my point of view our pipelines using our VMSS agent pool were on version >3.240.1 for at least a month, since we've been relying on a feature introduced in that version since then.

**Comment by angaaruriakhil** [comment]
We're seeing the same thing. With the new version of the extension, it's using the older version of the pipelines agent. I'm quite interested in why this downgrade has happened.

**Comment by ggeorge-pros** [comment]
I would add that I'd prefer a way to disable the extension completely. The extension does not support arm64 architectures even though the agent runtime supports it, because the extension configuration is specific to amd64. 

We have to create a custom agent startup script for our Kubernetes based agents, and it makes no sense why we can't choose to do that for VMSS agents, especially elastic ones.

**Comment by tkasparek** [comment]
Update: I've managed to root cause the issue. I will roll out the fix on Monday.

**Comment by martinm82** [comment]
Sorry to comment on an older ticket but we are using as well this extension and version 1.26 points in our case to agent version 3.236.0.

How can we update this version so that new pools will use the latest agent version? Also, since there is already version 4.x how could be configure to either use latest 3.x or 4.x versions?

<img width="562" alt="Image" src="https://github.com/user-attachments/assets/6aae71d7-bf34-4c9e-9f85-0e8ae4701823" />

**Comment by rybal06** [comment]
![Image](https://github.com/user-attachments/assets/bd8863b5-0ff1-44fd-87bd-132c03fdd56b)

In our tenant, I am seeing vsts-agent-linux-x64-4.255.0.tar.gz. Could you check again?

**Comment by martinm82** [comment]
We have Ubuntu 22.04 and the default agent installed is 3.236.0. So, I guess this is the default version for this specific Ubuntu version and I assume we need to manually update the agent.

**Comment by JeffreyH89** [comment]
Good afternoon, @tkasparek 

We are still experiencing the issue that our Linux VMSS is not upgraded to the latest pipelines agent.
Our scaleset is running Ubuntu 22.04, but the agent version is stuck on 3.236.0. 

<img width="714" height="561" alt="Image" src="https://github.com/user-attachments/assets/c6eeabae-bc9e-4824-9077-3bc753d8a201" />

Even after re-deploying/registering the agent pool nothing has changed.

Thank you,

Jeffrey

**Comment by martinm82** [comment]
Can someone please put some light on it and explain why certain people use extension version 1.26 and get an agent version 3.236 and others 4.255? How is that configurable.
